trigger:
    branches:
        include:
            - dev
            - test
            - acc
            - main

pool:
    name: 'PZH-Agent'

variables:
    VITE_API_ENV: $(Build.SourceBranchName)

stages:
    - stage: Build
      displayName: Build and Test the application
      jobs:
          - job:
            steps:
                # Cache node_modules for faster installs
                - task: Cache@2
                  inputs:
                      key: 'yarn | "$(Agent.OS)" | $(Build.SourcesDirectory)/yarn.lock'
                      restoreKeys: |
                          yarn | "$(Agent.OS)"
                      path: $(Build.SourcesDirectory)/.yarn/cache
                  displayName: Cache Yarn cache

                - task: NodeTool@0
                  inputs:
                      versionSpec: '18.x'
                  displayName: Install Node.js

                  # Enable Corepack
                - script: corepack enable
                  displayName: 'Enable Corepack'

                - task: CmdLine@2
                  displayName: 'Install dependencies'
                  inputs:
                      script: 'yarn --immutable'

                - task: CmdLine@2
                  displayName: Run the tests and generate coverage report
                  inputs:
                      script: yarn test:coverage

                - task: PublishCodeCoverageResults@1
                  inputs:
                      codeCoverageTool: Cobertura
                      summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml

                - task: CmdLine@2
                  displayName: Build
                  inputs:
                      script: yarn build

                - task: PublishBuildArtifacts@1
                  inputs:
                      PathtoPublish: $(Build.SourcesDirectory)/build
                      ArtifactName: BuildedApp_$(Build.BuildId)

    - stage: Dev
      displayName: Dev deploy
      dependsOn:
          - Build
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'dev'))
      jobs:
          - deployment:
            displayName: Dev deploy
            environment: Dev
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: azure-file-copy.yml
                              parameters:
                                  storageName: 'obfrontenddev'

    - stage: Test
      displayName: Test deploy
      dependsOn:
          - Build
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'test'))
      jobs:
          - deployment:
            displayName: Test deploy
            environment: Test
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: azure-file-copy.yml
                              parameters:
                                  storageName: 'obfrontendtest'
                            - template: azure-purge-cdn.yml
                              parameters:
                                  name: 'obzhtest'
                                  profileName: 'dta-obfrontendtest-cdn'

    - stage: Acc
      displayName: Acc deploy
      dependsOn:
          - Build
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'acc'))
      jobs:
          - deployment:
            displayName: Acc deploy
            environment: Acc
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: azure-file-copy.yml
                              parameters:
                                  storageName: 'obfrontendacc'
                            - template: azure-purge-cdn.yml
                              parameters:
                                  name: 'obzhacc'
                                  profileName: 'dta-obfrontendacc-cdn'

    - stage: Prod
      displayName: Prod deploy
      dependsOn:
          - Build
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
      jobs:
          - deployment:
            displayName: Prod deploy
            environment: Prod
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: azure-file-copy.yml
                              parameters:
                                  storageName: 'obfrontendprod'
                            - template: azure-purge-cdn.yml
                              parameters:
                                  name: 'obzhprod'
                                  profileName: 'dta-obfrontendprod-cdn'
