trigger:
    - dev
    - test
    - acc
    - production

pool:
    vmImage: 'windows-latest'

jobs:
    - job: Build
      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: '10.x'
            displayName: 'Install Node.js'

          - script: npm install
            displayName: 'Install dependencies'
          - script: Set VITE_API_ENV=$(Build.SourceBranchName)
            displayName: 'Set env'
          - script: npm run-script build
            displayName: 'Build'
          - task: PublishBuildArtifacts@1
            inputs:
                PathtoPublish: $(System.DefaultWorkingDirectory)/build
                ArtifactName: BuildedApp
