trigger: none
pr: none

parameters:
  - name: githubBranch
    displayName: GitHub branch to deploy
    type: string
    default: dev
    values:
       - dev
       - main
       - test

resources:
  repositories:
    - repository: githubCode
      type: github
      name: Provincie-Zuid-Holland/Omgevingsbeleid-Frontend
      endpoint: 'Provincie-Zuid-Holland'
      ref: refs/heads/${{ parameters.githubBranch }}

pool:
  name: "PZH-Ubuntu-Agent"

variables:
  VITE_API_ENV: ${{ parameters.githubBranch }}
  NODE_OPTIONS: --max_old_space_size=4096
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn/cache

stages:
  - stage: Build
    displayName: Build React App
    jobs:
      - job: Build
        steps:
          - checkout: githubCode
            path: app-omgb-fe

          - task: UseNode@1
            displayName: Install Node.js
            inputs:
              version: "22.x"

          - script: |
              corepack enable
            displayName: Configure Yarn
            workingDirectory: "$(Agent.BuildDirectory)/app-omgb-fe"

          - script: yarn --immutable
            displayName: Install dependencies
            workingDirectory: "$(Agent.BuildDirectory)/app-omgb-fe"

          - script: yarn build
            displayName: Build
            workingDirectory: "$(Agent.BuildDirectory)/app-omgb-fe"

          - publish: "$(Agent.BuildDirectory)/app-omgb-fe/build"
            artifact: "omgb_FE_build_$(Build.BuildId)"

  - stage: Deploy
    displayName: Deploy selected GitHub branch
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DevDeploy
        displayName: Deploy to Dev
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: "omgb_FE_build_$(Build.BuildId)"

                - task: AzureCLI@2
                  displayName: Deploy to Azure Blob Storage
                  inputs:
                    azureSubscription: "app-omgevingsbeleid-ont"
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az storage blob delete-batch \
                        --account-name "omgevingsbeleidontst" \
                        --source '$web' \
                        --auth-mode login \
                        --only-show-errors

                      az storage blob upload-batch \
                        --account-name "omgevingsbeleidontst" \
                        --destination '$web' \
                        --source "$(Pipeline.Workspace)/omgb_FE_build_$(Build.BuildId)" \
                        --auth-mode login \
                        --overwrite true \
                        --only-show-errors