trigger:
    branches:
        include:
            - dev
            - test
            - acc
            - main

pool:
    vmImage: 'windows-latest'

stages:
    - stage: Build
      jobs:
          - job:
            displayName: Build the application
            steps:
                - task: NodeTool@0
                  inputs:
                      versionSpec: '16.x'
                  displayName: 'Install Node.js'

                - task: CmdLine@2
                  displayName: 'Install dependencies'
                  inputs:
                      script: yarn install

                - task: CmdLine@2
                  displayName: 'Set env'
                  inputs:
                      script: echo "##vso[task.setvariable variable=VITE_API_ENV]$(Build.SourceBranchName)"

                - task: CmdLine@2
                  displayName: 'Build'
                  inputs:
                      script: yarn build

                - task: PublishBuildArtifacts@1
                  inputs:
                      PathtoPublish: $(System.DefaultWorkingDirectory)/build
                      ArtifactName: BuildedApp

    - stage: Dev
      dependsOn:
          - Build
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'dev'))
      jobs:
          - deployment:
            displayName: Dev deploy
            environment: Dev
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: azure-file-copy.yml
                              parameters:
                                  storageName: 'obfrontenddev'

    - stage: Test
      dependsOn:
          - Build
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'test'))
      jobs:
          - deployment:
            displayName: Test deploy
            environment: Test
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: azure-file-copy.yml
                              parameters:
                                  storageName: 'obfrontendtest'

    # - stage: Test
    #   dependsOn:
    #       - Dev
    #   jobs:
    #       - deployment:
    #         displayName: Test deploy
    #         environment: Test
    #         strategy:
    #             runOnce:
    #                 deploy:
    #                     steps:
    #                         - task: CmdLine@2
    #                           displayName: 'Set env'
    #                           inputs:
    #                               script: export VITE_API_ENV=test

    #                         - task: CmdLine@2
    #                           displayName: 'Build'
    #                           inputs:
    #                               script: yarn build

    #                         - script: echo Running in the Test environment as deployment job
    #                           displayName: 'Test based stage'

    # - stage: Acc
    #   dependsOn:
    #       - Test
    #   jobs:
    #       - deployment:
    #         displayName: Acc deploy
    #         environment: Acc
    #         strategy:
    #             runOnce:
    #                 deploy:
    #                     steps:
    #                         - task: CmdLine@2
    #                           displayName: 'Set env'
    #                           inputs:
    #                               script: export VITE_API_ENV=acc

    #                         - task: CmdLine@2
    #                           displayName: 'Build'
    #                           inputs:
    #                               script: yarn build

    #                         - script: echo Running in the Acc environment as deployment job
    #                           displayName: 'Acc based stage'
