trigger:
    branches:
        include:
            - dev
            - test
            - acc
            - production

pool:
    #vmImage: windows-latest
    name: 'PZH-Ubuntu-Agent'

stages:
    - stage: Build
      jobs:
          - job:
            displayName: Build the application
            steps:
                - task: NodeTool@0
                  inputs:
                      versionSpec: '16.17.x'
                  displayName: 'Install Node.js'

                - task: CmdLine@2
                  displayName: 'Install dependencies'
                  inputs:
                      script: yarn install

                - task: CmdLine@2
                  displayName: 'Set env'
                  inputs:
                      script: export VITE_API_ENV=$(Build.SourceBranchName)

                - task: CmdLine@2
                  displayName: 'Build'
                  inputs:
                      script: yarn build

                - task: PublishBuildArtifacts@1
                  inputs:
                      PathtoPublish: $(System.DefaultWorkingDirectory)/build
                      ArtifactName: BuildedApp

    - stage: Dev
      dependsOn:
          - Build
      jobs:
          - deployment:
            displayName: Development deploy
            environment: Development
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - script: export VITE_API_ENV=dev
                            - script: yarn build
                            - script: echo Running in the Dev environment as deployment job

    - stage: Test
      dependsOn:
          - Dev
      jobs:
          - deployment:
            displayName: Test deploy
            environment: Test
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - task: CmdLine@2
                              displayName: 'Set env'
                              inputs:
                                  script: export VITE_API_ENV=test

                            - task: CmdLine@2
                              displayName: 'Build'
                              inputs:
                                  script: yarn build

                            - script: echo Running in the Test environment as deployment job
                              displayName: 'Test based stage'

    - stage: Acceptation
      dependsOn:
          - Test
      jobs:
          - deployment:
            displayName: Acceptation deploy
            environment: Acceptation
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - task: CmdLine@2
                              displayName: 'Set env'
                              inputs:
                                  script: export VITE_API_ENV=acc

                            - task: CmdLine@2
                              displayName: 'Build'
                              inputs:
                                  script: yarn build

                            - script: echo Running in the Acceptation environment as deployment job
                              displayName: 'Acceptation based stage'
