trigger:
    branches:
        include:
            - dev
            - test
            - acc
            - main

pool:
    name: 'PZH-Agent'

variables:
    VITE_API_ENV: $(Build.SourceBranchName)
    NODE_OPTIONS: --max_old_space_size=4096
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn/cache

stages:
    - stage: Build
      displayName: Build and test application
      jobs:
          - job: Build
            displayName: Install, test and build
            steps:
                - task: Cache@2
                  displayName: Cache Yarn
                  inputs:
                      key: 'yarn | "$(Agent.OS)" | yarn.lock'
                      restoreKeys: |
                          yarn | "$(Agent.OS)"
                      path: $(YARN_CACHE_FOLDER)

                - task: NodeTool@0
                  displayName: Install Node.js
                  inputs:
                      versionSpec: '22.x'

                - script: |
                      corepack enable
                      yarn config set cacheFolder $(YARN_CACHE_FOLDER)
                  displayName: Enable Corepack and configure Yarn cache

                - script: yarn --immutable
                  displayName: Install dependencies

                - script: yarn test
                  displayName: Run tests
                  condition: ne(variables['Build.SourceBranchName'], 'main')

                - script: yarn test:coverage
                  displayName: Run tests with coverage
                  condition: eq(variables['Build.SourceBranchName'], 'main')

                - task: PublishCodeCoverageResults@2
                  displayName: Publish code coverage
                  condition: eq(variables['Build.SourceBranchName'], 'main')
                  inputs:
                      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'

                - script: yarn build
                  displayName: Build

                - task: PublishBuildArtifacts@1
                  displayName: Publish build artifact
                  inputs:
                      PathtoPublish: $(Build.SourcesDirectory)/build
                      ArtifactName: BuildedApp_$(Build.BuildId)

    - stage: Dev
      displayName: Dev deploy
      dependsOn: Build
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'dev'))
      jobs:
          - deployment: DevDeploy
            displayName: Dev deploy
            environment: Dev
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: azure-file-copy.yml
                              parameters:
                                  storageName: obfrontenddev

    - stage: Test
      displayName: Test deploy
      dependsOn: Build
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'test'))
      jobs:
          - deployment: TestDeploy
            displayName: Test deploy
            environment: Test
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: azure-file-copy.yml
                              parameters:
                                  storageName: obfrontendtest

    - stage: Acc
      displayName: Acc deploy
      dependsOn: Build
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'acc'))
      jobs:
          - deployment: AccDeploy
            displayName: Acc deploy
            environment: Acc
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: azure-file-copy.yml
                              parameters:
                                  storageName: obfrontendacc

    - stage: Prod
      displayName: Prod deploy
      dependsOn: Build
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
      jobs:
          - deployment: ProdDeploy
            displayName: Prod deploy
            environment: Prod
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: azure-file-copy.yml
                              parameters:
                                  storageName: obfrontendprod

                            - template: azure-purge-cdn.yml
                              parameters:
                                  name: obzhprod
                                  profileName: dta-obfrontendprod-cdn
