trigger:
    branches:
        include:
            - dev
            - test
            - acc
            - main

pool:
    name: 'PZH-Agent'

variables:
    subscription: 'dta-omgevingsbeleid'

stages:
    - stage: Build
      jobs:
          - job:
            displayName: Build the application
            steps:
                - task: NodeTool@0
                  inputs:
                      versionSpec: '16.x'
                  displayName: 'Install Node.js'

                - task: CmdLine@2
                  displayName: 'Install dependencies'
                  inputs:
                      script: yarn install

                - task: CmdLine@2
                  displayName: 'Set env'
                  inputs:
                      script: echo "##vso[task.setvariable variable=VITE_API_ENV]$(Build.SourceBranchName)"

                - task: CmdLine@2
                  displayName: 'Build'
                  inputs:
                      script: yarn build

                - task: PublishBuildArtifacts@1
                  inputs:
                      PathtoPublish: $(Build.SourcesDirectory)/build
                      ArtifactName: BuildedApp

    - stage: Dev
      dependsOn:
          - Build
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'dev'))
      jobs:
          - deployment:
            displayName: Dev deploy
            environment: Dev
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: azure-file-copy.yml
                              parameters:
                                  storageName: 'obfrontenddev'

    - stage: Test
      dependsOn:
          - Build
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'test'))
      jobs:
          - deployment:
            displayName: Test deploy
            environment: Test
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: azure-file-copy.yml
                              parameters:
                                  storageName: 'obfrontendtest'
