const objecten = {
    belangen: {
        buttonTekst: 'belang',
        volledigeTitel: 'Nationaal Belang',
        volledigeTitelMeervoud: 'Nationale Belangen',
        api: '/belangen',
        filterAPI: true,
        filterType: 'Nationaal Belang',
        propertyName: 'Belangen',
        type: 'Nationaal Belang',
    },
    taken: {
        buttonTekst: 'taak',
        volledigeTitel: 'Wettelijke taken & bevoegdheden',
        volledigeTitelMeervoud: 'Wettelijke taken & bevoegdheden',
        api: '/belangen',
        filterAPI: true,
        filterType: 'Wettelijke Taak & Bevoegdheid',
        propertyName: 'Belangen',
        type: 'Wettelijke Taak & Bevoegdheid',
    },
    ambities: {
        buttonTekst: 'ambities',
        volledigeTitel: 'Ambities',
        volledigeTitelMeervoud: 'Ambities',
        api: '/ambities',
        propertyName: 'Ambities',
        type: 'Ambitie',
    },
    beleidsdoelen: {
        buttonTekst: 'beleidsdoelen',
        volledigeTitel: 'Beleidsdoelen',
        volledigeTitelMeervoud: 'Beleidsdoelen',
        api: '/beleidsdoelen',
        propertyName: 'Beleidsdoelen',
        type: 'Beleidsdoel',
    },
    themas: {
        buttonTekst: 'themas',
        volledigeTitel: 'Themas',
        volledigeTitelMeervoud: 'Themas',
        api: '/themas',
        propertyName: 'Themas',
        type: 'Thema',
    },
    beleidsprestaties: {
        buttonTekst: 'beleidsprestaties',
        volledigeTitel: 'Beleidsprestaties',
        volledigeTitelMeervoud: 'Beleidsprestaties',
        api: '/beleidsprestaties',
        propertyName: 'Beleidsprestaties',
        type: 'Beleidsprestatie',
    },
    maatregelen: {
        buttonTekst: 'maatregelen',
        volledigeTitel: 'Maatregelen',
        volledigeTitelMeervoud: 'Maatregelen',
        api: '/maatregelen',
        propertyName: 'Maatregelen',
        type: 'Maatregel',
    },
    verordening: {
        buttonTekst: 'verordeningen',
        volledigeTitel: 'Verordening',
        volledigeTitelMeervoud: 'Verordeningen',
        api: '/verordeningen',
        propertyName: 'Verordening',
        type: 'Verordening',
    },
    beleidsregels: {
        buttonTekst: 'beleidsregels',
        volledigeTitel: 'Beleidsregels',
        volledigeTitelMeervoud: 'Beleidsregels',
        api: '/beleidsregels',
        propertyName: 'BeleidsRegels',
        type: 'Beleidsregel',
    },
}

export default objecten
