/**
 * Generated by orval v6.5.1 🍺
 * Do not edit manually.
 * Omgevingsbeleid API
 * This API serves all the object that make up the policies of a provincial government
 * OpenAPI spec version: 0.0.2
 */
export type GetWerkingsgebiedenLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetWerkingsgebiedenLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetWerkingsgebieden400 = {
    /** A description of the invalid filters */
    message?: string
}

export type GetWerkingsgebiedenParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetVersionWerkingsgebiedenObjectuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetVersionVerordeningenObjectuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetVersionThemasObjectuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetVersionMaatregelenObjectuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetVersionBeleidsrelatiesObjectuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetVersionBeleidsregelsObjectuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetVersionBeleidsprestatiesObjectuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetVersionBeleidsmodulesObjectuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetVersionBeleidskeuzesObjectuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetVersionBeleidsdoelenObjectuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetVersionBelangenObjectuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetVersionAmbitiesObjectuuid404 = {
    /** A description of the error */
    message?: string
}

export type PatchVerordeningenLineageid500 = {
    /** A description of the error */
    message?: string
}

export type PatchVerordeningenLineageid403 = {
    /** A description of the error */
    message?: string
}

export type PatchVerordeningenLineageid400 = {
    /** A description of the error */
    message?: string
}

export type GetVerordeningenLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetVerordeningenLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PostVerordeningen500 = {
    /** A description of the error */
    message?: string
}

export type PostVerordeningen403 = {
    /** A description of the error */
    message?: string
}

export type PostVerordeningen400 = {
    /** A description of the error */
    message?: string
}

export type GetVerordeningen400 = {
    /** A description of the invalid filters */
    message?: string
}

export type GetVerordeningenParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidWerkingsgebiedenLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetValidWerkingsgebiedenLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidWerkingsgebieden404 = {
    /** A description of the error */
    message?: string
}

export type GetValidWerkingsgebiedenParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidVerordeningenLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetValidVerordeningenLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidVerordeningen404 = {
    /** A description of the error */
    message?: string
}

export type GetValidVerordeningenParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidThemasLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetValidThemasLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidThemas404 = {
    /** A description of the error */
    message?: string
}

export type GetValidThemasParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidMaatregelenLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetValidMaatregelenLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidMaatregelen404 = {
    /** A description of the error */
    message?: string
}

export type GetValidMaatregelenParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBeleidsrelatiesLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBeleidsrelatiesLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBeleidsrelaties404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBeleidsrelatiesParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBeleidsregelsLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBeleidsregelsLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBeleidsregels404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBeleidsregelsParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBeleidsprestatiesLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBeleidsprestatiesLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBeleidsprestaties404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBeleidsprestatiesParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBeleidsmodulesLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBeleidsmodulesLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBeleidsmodules404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBeleidsmodulesParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBeleidskeuzesLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBeleidskeuzesLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBeleidskeuzes404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBeleidskeuzesParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBeleidsdoelenLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBeleidsdoelenLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBeleidsdoelen404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBeleidsdoelenParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBelangenLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBelangenLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidBelangen404 = {
    /** A description of the error */
    message?: string
}

export type GetValidBelangenParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidAmbitiesLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetValidAmbitiesLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetValidAmbities404 = {
    /** A description of the error */
    message?: string
}

export type GetValidAmbitiesParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetTokeninfo200Identifier = {
    /** Email for the user that generated this token */
    Email?: string
    /** Username for the user that generated this token */
    Gebruikersnaam?: string
    /** Role for the user that generated this token */
    Rol?: string
    /** UUID for the user that generated this token */
    UUID?: string
}

export type GetTokeninfo200 = {
    /** Moment of expiration for this token */
    expires?: string
    identifier?: GetTokeninfo200Identifier
}

export type PatchThemasLineageid500 = {
    /** A description of the error */
    message?: string
}

export type PatchThemasLineageid403 = {
    /** A description of the error */
    message?: string
}

export type PatchThemasLineageid400 = {
    /** A description of the error */
    message?: string
}

export type GetThemasLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetThemasLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PostThemas500 = {
    /** A description of the error */
    message?: string
}

export type PostThemas403 = {
    /** A description of the error */
    message?: string
}

export type PostThemas400 = {
    /** A description of the error */
    message?: string
}

export type GetThemas400 = {
    /** A description of the invalid filters */
    message?: string
}

export type GetThemasParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetSearch403 = {
    /** A description of the error */
    message?: string
}

export type GetSearch400 = {
    /** A description of the error */
    message?: string
}

/**
 * The type of this object
 */
export type GetSearch200ItemType =
    | 'beleidskeuzes'
    | 'ambities'
    | 'belangen'
    | 'beleidsdoelen'
    | 'beleidsprestaties'
    | 'beleidsregels'
    | 'maatregelen'
    | 'themas'

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSearch200ItemType = {
    beleidskeuzes: 'beleidskeuzes' as GetSearch200ItemType,
    ambities: 'ambities' as GetSearch200ItemType,
    belangen: 'belangen' as GetSearch200ItemType,
    beleidsdoelen: 'beleidsdoelen' as GetSearch200ItemType,
    beleidsprestaties: 'beleidsprestaties' as GetSearch200ItemType,
    beleidsregels: 'beleidsregels' as GetSearch200ItemType,
    maatregelen: 'maatregelen' as GetSearch200ItemType,
    themas: 'themas' as GetSearch200ItemType,
}

export type GetSearch200Item = {
    /** A description of this object */
    Omschrijving?: string
    /** A representation of the search rank, only usefull for comparing between two results */
    RANK?: number
    /** The title of this object */
    Titel?: string
    /** The type of this object */
    Type?: GetSearch200ItemType
    /** The UUID of this object */
    UUID?: string
}

export type GetSearchParams = {
    query: string
    only?: string
    exclude?: string
    limit?: number
    offset?: number
}

export type PostPasswordreset401 = {
    /** An error message */
    message?: string
}

export type PostPasswordreset400 = {
    errors?: string[]
    /** An error message */
    message?: string
}

export type PostPasswordreset200 = {
    /** A success message */
    message?: string
}

export type PostPasswordresetBody = {
    /** The new password for this user */
    new_password?: string
    /** The current password for this user */
    password?: string
}

export type PatchMaatregelenLineageid500 = {
    /** A description of the error */
    message?: string
}

export type PatchMaatregelenLineageid403 = {
    /** A description of the error */
    message?: string
}

export type PatchMaatregelenLineageid400 = {
    /** A description of the error */
    message?: string
}

export type GetMaatregelenLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetMaatregelenLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PostMaatregelen500 = {
    /** A description of the error */
    message?: string
}

export type PostMaatregelen403 = {
    /** A description of the error */
    message?: string
}

export type PostMaatregelen400 = {
    /** A description of the error */
    message?: string
}

export type GetMaatregelen400 = {
    /** A description of the invalid filters */
    message?: string
}

export type GetMaatregelenParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PostLogin401 = {
    /** An error message */
    message?: string
}

export type PostLogin400 = {
    /** An error message specifying what is missing */
    message?: string
}

export type PostLogin200 = {
    /** A JWT token that can be used to make authorized request */
    access_token?: string
    /** The api deployment (DEV, TEST or ACC) */
    'deployment type'?: string
    /** Datetime of the expiration for this token */
    expires?: string
    /** The logged in user */
    identifier?: GebruikersRead
}

export type PostLoginBody = {
    /** Email adress for an user */
    identifier?: string
    /** password for an user */
    password?: string
}

export type GetGraph200NodesItem = {
    /** The title of the object this node represents */
    Titel?: string
    /** The type slug of the object this node represents */
    Type?: string
    /** The UUID of the object this node represents */
    UUID?: string
}

export type GetGraph200LinksItem = {
    /** The UUID of the object this link originates from */
    source?: string
    /** The UUID of the object this link targets to */
    target?: string
    /** The type slug of the object this link represents */
    type?: string
}

export type GetGraph200 = {
    links?: GetGraph200LinksItem[]
    nodes?: GetGraph200NodesItem[]
}

/**
 * Type slug for this object
 */
export type GetEdits200ItemType =
    | 'beleidsrelaties'
    | 'beleidsmodules'
    | 'beleidskeuzes'
    | 'ambities'
    | 'belangen'
    | 'beleidsdoelen'
    | 'beleidsprestaties'
    | 'beleidsregels'
    | 'maatregelen'
    | 'themas'
    | 'werkingsgebieden'
    | 'verordeningen'

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetEdits200ItemType = {
    beleidsrelaties: 'beleidsrelaties' as GetEdits200ItemType,
    beleidsmodules: 'beleidsmodules' as GetEdits200ItemType,
    beleidskeuzes: 'beleidskeuzes' as GetEdits200ItemType,
    ambities: 'ambities' as GetEdits200ItemType,
    belangen: 'belangen' as GetEdits200ItemType,
    beleidsdoelen: 'beleidsdoelen' as GetEdits200ItemType,
    beleidsprestaties: 'beleidsprestaties' as GetEdits200ItemType,
    beleidsregels: 'beleidsregels' as GetEdits200ItemType,
    maatregelen: 'maatregelen' as GetEdits200ItemType,
    themas: 'themas' as GetEdits200ItemType,
    werkingsgebieden: 'werkingsgebieden' as GetEdits200ItemType,
    verordeningen: 'verordeningen' as GetEdits200ItemType,
}

export type GetEdits200Item = {
    /** ID for this object */
    ID?: number
    /** The date when this edit was performed */
    Modified_Date?: string
    /** Status for this object */
    Status?: string
    /** Title for this object */
    Titel?: string
    /** Type slug for this object */
    Type?: GetEdits200ItemType
    /** UUID for this object */
    UUID?: string
}

export type GetChangesWerkingsgebiedenOlduuidNewuuid500 = {
    /** A description of the error */
    message?: string
}

export type GetChangesWerkingsgebiedenOlduuidNewuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetChangesWerkingsgebiedenOlduuidNewuuid200 = {
    changes?: WerkingsgebiedenChange
    old?: WerkingsgebiedenRead
}

export type GetChangesVerordeningenOlduuidNewuuid500 = {
    /** A description of the error */
    message?: string
}

export type GetChangesVerordeningenOlduuidNewuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetChangesVerordeningenOlduuidNewuuid200 = {
    changes?: VerordeningenChange
    old?: VerordeningenRead
}

export type GetChangesThemasOlduuidNewuuid500 = {
    /** A description of the error */
    message?: string
}

export type GetChangesThemasOlduuidNewuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetChangesThemasOlduuidNewuuid200 = {
    changes?: ThemasChange
    old?: ThemasRead
}

export type GetChangesMaatregelenOlduuidNewuuid500 = {
    /** A description of the error */
    message?: string
}

export type GetChangesMaatregelenOlduuidNewuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetChangesMaatregelenOlduuidNewuuid200 = {
    changes?: MaatregelenChange
    old?: MaatregelenRead
}

export type GetChangesBeleidsrelatiesOlduuidNewuuid500 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBeleidsrelatiesOlduuidNewuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBeleidsrelatiesOlduuidNewuuid200 = {
    changes?: BeleidsrelatiesChange
    old?: BeleidsrelatiesRead
}

export type GetChangesBeleidsregelsOlduuidNewuuid500 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBeleidsregelsOlduuidNewuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBeleidsregelsOlduuidNewuuid200 = {
    changes?: BeleidsregelsChange
    old?: BeleidsregelsRead
}

export type GetChangesBeleidsprestatiesOlduuidNewuuid500 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBeleidsprestatiesOlduuidNewuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBeleidsprestatiesOlduuidNewuuid200 = {
    changes?: BeleidsprestatiesChange
    old?: BeleidsprestatiesRead
}

export type GetChangesBeleidsmodulesOlduuidNewuuid500 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBeleidsmodulesOlduuidNewuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBeleidsmodulesOlduuidNewuuid200 = {
    changes?: BeleidsmodulesChange
    old?: BeleidsmodulesRead
}

export type GetChangesBeleidskeuzesOlduuidNewuuid500 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBeleidskeuzesOlduuidNewuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBeleidskeuzesOlduuidNewuuid200 = {
    changes?: BeleidskeuzesChange
    old?: BeleidskeuzesRead
}

export type GetChangesBeleidsdoelenOlduuidNewuuid500 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBeleidsdoelenOlduuidNewuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBeleidsdoelenOlduuidNewuuid200 = {
    changes?: BeleidsdoelenChange
    old?: BeleidsdoelenRead
}

export type GetChangesBelangenOlduuidNewuuid500 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBelangenOlduuidNewuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetChangesBelangenOlduuidNewuuid200 = {
    changes?: BelangenChange
    old?: BelangenRead
}

export type GetChangesAmbitiesOlduuidNewuuid500 = {
    /** A description of the error */
    message?: string
}

export type GetChangesAmbitiesOlduuidNewuuid404 = {
    /** A description of the error */
    message?: string
}

export type GetChangesAmbitiesOlduuidNewuuid200 = {
    changes?: AmbitiesChange
    old?: AmbitiesRead
}

export type GetBeleidsrelatiesLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidsrelatiesLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type GetBeleidsrelaties400 = {
    /** A description of the invalid filters */
    message?: string
}

export type GetBeleidsrelatiesParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PatchBeleidsregelsLineageid500 = {
    /** A description of the error */
    message?: string
}

export type PatchBeleidsregelsLineageid403 = {
    /** A description of the error */
    message?: string
}

export type PatchBeleidsregelsLineageid400 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidsregelsLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidsregelsLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PostBeleidsregels500 = {
    /** A description of the error */
    message?: string
}

export type PostBeleidsregels403 = {
    /** A description of the error */
    message?: string
}

export type PostBeleidsregels400 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidsregels400 = {
    /** A description of the invalid filters */
    message?: string
}

export type GetBeleidsregelsParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PatchBeleidsprestatiesLineageid500 = {
    /** A description of the error */
    message?: string
}

export type PatchBeleidsprestatiesLineageid403 = {
    /** A description of the error */
    message?: string
}

export type PatchBeleidsprestatiesLineageid400 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidsprestatiesLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidsprestatiesLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PostBeleidsprestaties500 = {
    /** A description of the error */
    message?: string
}

export type PostBeleidsprestaties403 = {
    /** A description of the error */
    message?: string
}

export type PostBeleidsprestaties400 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidsprestaties400 = {
    /** A description of the invalid filters */
    message?: string
}

export type GetBeleidsprestatiesParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PatchBeleidsmodulesLineageid500 = {
    /** A description of the error */
    message?: string
}

export type PatchBeleidsmodulesLineageid403 = {
    /** A description of the error */
    message?: string
}

export type PatchBeleidsmodulesLineageid400 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidsmodulesLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidsmodulesLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PostBeleidsmodules500 = {
    /** A description of the error */
    message?: string
}

export type PostBeleidsmodules403 = {
    /** A description of the error */
    message?: string
}

export type PostBeleidsmodules400 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidsmodules400 = {
    /** A description of the invalid filters */
    message?: string
}

export type GetBeleidsmodulesParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PatchBeleidskeuzesLineageid500 = {
    /** A description of the error */
    message?: string
}

export type PatchBeleidskeuzesLineageid403 = {
    /** A description of the error */
    message?: string
}

export type PatchBeleidskeuzesLineageid400 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidskeuzesLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidskeuzesLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PostBeleidskeuzes500 = {
    /** A description of the error */
    message?: string
}

export type PostBeleidskeuzes403 = {
    /** A description of the error */
    message?: string
}

export type PostBeleidskeuzes400 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidskeuzes400 = {
    /** A description of the invalid filters */
    message?: string
}

export type GetBeleidskeuzesParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PatchBeleidsdoelenLineageid500 = {
    /** A description of the error */
    message?: string
}

export type PatchBeleidsdoelenLineageid403 = {
    /** A description of the error */
    message?: string
}

export type PatchBeleidsdoelenLineageid400 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidsdoelenLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidsdoelenLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PostBeleidsdoelen500 = {
    /** A description of the error */
    message?: string
}

export type PostBeleidsdoelen403 = {
    /** A description of the error */
    message?: string
}

export type PostBeleidsdoelen400 = {
    /** A description of the error */
    message?: string
}

export type GetBeleidsdoelen400 = {
    /** A description of the invalid filters */
    message?: string
}

export type GetBeleidsdoelenParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PatchBelangenLineageid500 = {
    /** A description of the error */
    message?: string
}

export type PatchBelangenLineageid403 = {
    /** A description of the error */
    message?: string
}

export type PatchBelangenLineageid400 = {
    /** A description of the error */
    message?: string
}

export type GetBelangenLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetBelangenLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PostBelangen500 = {
    /** A description of the error */
    message?: string
}

export type PostBelangen403 = {
    /** A description of the error */
    message?: string
}

export type PostBelangen400 = {
    /** A description of the error */
    message?: string
}

export type GetBelangen400 = {
    /** A description of the invalid filters */
    message?: string
}

export type GetBelangenParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PatchAmbitiesLineageid500 = {
    /** A description of the error */
    message?: string
}

export type PatchAmbitiesLineageid403 = {
    /** A description of the error */
    message?: string
}

export type PatchAmbitiesLineageid400 = {
    /** A description of the error */
    message?: string
}

export type GetAmbitiesLineageid404 = {
    /** A description of the error */
    message?: string
}

export type GetAmbitiesLineageidParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

export type PostAmbities500 = {
    /** A description of the error */
    message?: string
}

export type PostAmbities403 = {
    /** A description of the error */
    message?: string
}

export type PostAmbities400 = {
    /** A description of the error */
    message?: string
}

export type GetAmbities400 = {
    /** A description of the invalid filters */
    message?: string
}

export type GetAmbitiesParams = {
    all_filters?: string
    any_filters?: string
    limit?: number
    offset?: number
}

/**
 * Schema that defines how to write werkingsgebieden
 */
export interface WerkingsgebiedenWrite {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Eind_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Werkingsgebied?: string
    /** None */
    symbol?: string
}

/**
 * Schema that defines the structure of werkingsgebieden when reading
 */
export interface WerkingsgebiedenRead {
    /** None */
    Begin_Geldigheid?: string
    /** An inlined gebruikers object */
    Created_By?: GebruikersInline
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** An inlined gebruikers object */
    Modified_By?: GebruikersInline
    /** None */
    Modified_Date?: string
    /** None */
    UUID?: string
    /** None */
    Werkingsgebied?: string
    /** None */
    symbol?: string
}

/**
 * Schema that defines the structure of werkingsgebieden when inlining
 */
export interface WerkingsgebiedenInline {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Modified_Date?: string
    /** None */
    UUID?: string
    /** None */
    Werkingsgebied?: string
    /** None */
    symbol?: string
}

/**
 * Schema that defines the structure of werkingsgebieden when looking at changes
 */
export interface WerkingsgebiedenChange {
    /** None */
    Begin_Geldigheid?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** None */
    Modified_Date?: string
    /** None */
    UUID?: string
    /** None */
    Werkingsgebied?: string
    /** None */
    symbol?: string
}

/**
 * Schema that defines how to write verordeningen
 */
export interface VerordeningenWrite {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** A UUID reference to a gebruikers object */
    Eigenaar_1?: string
    /** A UUID reference to a gebruikers object */
    Eigenaar_2?: string
    /** None */
    Eind_Geldigheid?: string
    /** A UUID reference to a werkingsgebieden object */
    Gebied?: string
    /** None */
    Inhoud?: string
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** A UUID reference to a gebruikers object */
    Opdrachtgever?: string
    /** A UUID reference to a gebruikers object */
    Portefeuillehouder_1?: string
    /** A UUID reference to a gebruikers object */
    Portefeuillehouder_2?: string
    /** None */
    Status?: string
    /** None */
    Titel?: string
    /** None */
    Type?: string
    /** None */
    Volgnummer?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of verordeningen when reading
 */
export interface VerordeningenRead {
    /** None */
    Begin_Geldigheid?: string
    /** An inlined gebruikers object */
    Created_By?: GebruikersInline
    /** None */
    Created_Date?: string
    /** An inlined gebruikers object */
    Eigenaar_1?: GebruikersInline
    /** An inlined gebruikers object */
    Eigenaar_2?: GebruikersInline
    /** None */
    Eind_Geldigheid?: string
    /** An inlined werkingsgebieden object */
    Gebied?: WerkingsgebiedenInline
    /** None */
    ID?: number
    /** None */
    Inhoud?: string
    /** An inlined gebruikers object */
    Modified_By?: GebruikersInline
    /** None */
    Modified_Date?: string
    /** An inlined gebruikers object */
    Opdrachtgever?: GebruikersInline
    /** An inlined gebruikers object */
    Portefeuillehouder_1?: GebruikersInline
    /** An inlined gebruikers object */
    Portefeuillehouder_2?: GebruikersInline
    /** An list of beleidskeuze-short objects that refer to this object (reverse lookup) */
    Ref_Beleidskeuzes?: BeleidskeuzeShortInline[]
    /** None */
    Status?: string
    /** None */
    Titel?: string
    /** None */
    Type?: string
    /** None */
    UUID?: string
    /** None */
    Volgnummer?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of verordeningen when inlining
 */
export interface VerordeningenInline {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Created_Date?: string
    /** A UUID reference to a gebruikers object */
    Eigenaar_1?: string
    /** A UUID reference to a gebruikers object */
    Eigenaar_2?: string
    /** None */
    Eind_Geldigheid?: string
    /** A UUID reference to a werkingsgebieden object */
    Gebied?: string
    /** None */
    ID?: number
    /** None */
    Inhoud?: string
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Modified_Date?: string
    /** A UUID reference to a gebruikers object */
    Opdrachtgever?: string
    /** A UUID reference to a gebruikers object */
    Portefeuillehouder_1?: string
    /** A UUID reference to a gebruikers object */
    Portefeuillehouder_2?: string
    /** None */
    Status?: string
    /** None */
    Titel?: string
    /** None */
    Type?: string
    /** None */
    UUID?: string
    /** None */
    Volgnummer?: string
    /** None */
    Weblink?: string
}

/**
 * An object that shows the changes in the list
 */
export type VerordeningenChangeRefBeleidskeuzes = {
    new?: BeleidskeuzeShortInline[]
    removed?: BeleidskeuzeShortInline[]
    same?: BeleidskeuzeShortInline[]
}

/**
 * Schema that defines the structure of verordeningen when looking at changes
 */
export interface VerordeningenChange {
    /** None */
    Begin_Geldigheid?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** None */
    Inhoud?: string
    /** None */
    Modified_Date?: string
    /** An object that shows the changes in the list */
    Ref_Beleidskeuzes?: VerordeningenChangeRefBeleidskeuzes
    /** None */
    Status?: string
    /** None */
    Titel?: string
    /** None */
    Type?: string
    /** None */
    UUID?: string
    /** None */
    Volgnummer?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines how to write themas
 */
export interface ThemasWrite {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Eind_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Omschrijving?: string
    /** None */
    Titel?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of themas when reading
 */
export interface ThemasRead {
    /** None */
    Begin_Geldigheid?: string
    /** An inlined gebruikers object */
    Created_By?: GebruikersInline
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** An inlined gebruikers object */
    Modified_By?: GebruikersInline
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An list of beleidskeuze-short objects that refer to this object (reverse lookup) */
    Ref_Beleidskeuzes?: BeleidskeuzeShortInline[]
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of themas when inlining
 */
export interface ThemasInline {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * An object that shows the changes in the list
 */
export type ThemasChangeRefBeleidskeuzes = {
    new?: BeleidskeuzeShortInline[]
    removed?: BeleidskeuzeShortInline[]
    same?: BeleidskeuzeShortInline[]
}

/**
 * Schema that defines the structure of themas when looking at changes
 */
export interface ThemasChange {
    /** None */
    Begin_Geldigheid?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An object that shows the changes in the list */
    Ref_Beleidskeuzes?: ThemasChangeRefBeleidskeuzes
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines how to write maatregelen
 */
export interface MaatregelenWrite {
    /** None */
    Aanpassing_Op?: string
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** A UUID reference to a gebruikers object */
    Eigenaar_1?: string
    /** A UUID reference to a gebruikers object */
    Eigenaar_2?: string
    /** None */
    Eind_Geldigheid?: string
    /** A UUID reference to a werkingsgebieden object */
    Gebied?: string
    /** None */
    Gebied_Duiding?: string
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Omschrijving?: string
    /** A UUID reference to a gebruikers object */
    Opdrachtgever?: string
    /** A UUID reference to a gebruikers object */
    Portefeuillehouder_1?: string
    /** A UUID reference to a gebruikers object */
    Portefeuillehouder_2?: string
    /** None */
    Status?: string
    /** None */
    Tags?: string
    /** None */
    Titel?: string
    /** None */
    Toelichting?: string
    /** None */
    Toelichting_Raw?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of maatregelen when reading
 */
export interface MaatregelenRead {
    /** None */
    Aanpassing_Op?: string
    /** None */
    Begin_Geldigheid?: string
    /** An inlined gebruikers object */
    Created_By?: GebruikersInline
    /** None */
    Created_Date?: string
    /** None */
    Effective_Version?: string
    /** An inlined gebruikers object */
    Eigenaar_1?: GebruikersInline
    /** An inlined gebruikers object */
    Eigenaar_2?: GebruikersInline
    /** None */
    Eind_Geldigheid?: string
    /** An inlined werkingsgebieden object */
    Gebied?: WerkingsgebiedenInline
    /** None */
    Gebied_Duiding?: string
    /** None */
    ID?: number
    /** None */
    Latest_Status?: string
    /** None */
    Latest_Version?: string
    /** An inlined gebruikers object */
    Modified_By?: GebruikersInline
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An inlined gebruikers object */
    Opdrachtgever?: GebruikersInline
    /** An inlined gebruikers object */
    Portefeuillehouder_1?: GebruikersInline
    /** An inlined gebruikers object */
    Portefeuillehouder_2?: GebruikersInline
    /** An list of beleidskeuze-short objects that refer to this object (reverse lookup) */
    Ref_Beleidskeuzes?: BeleidskeuzeShortInline[]
    /** An list of beleidsmodule-short objects that refer to this object (reverse lookup) */
    Ref_Beleidsmodules?: BeleidsmoduleShortInline[]
    /** None */
    Status?: string
    /** None */
    Tags?: string
    /** None */
    Titel?: string
    /** None */
    Toelichting?: string
    /** None */
    Toelichting_Raw?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of maatregelen when inlining
 */
export interface MaatregelenInline {
    /** None */
    Aanpassing_Op?: string
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Created_Date?: string
    /** A UUID reference to a gebruikers object */
    Eigenaar_1?: string
    /** A UUID reference to a gebruikers object */
    Eigenaar_2?: string
    /** None */
    Eind_Geldigheid?: string
    /** A UUID reference to a werkingsgebieden object */
    Gebied?: string
    /** None */
    Gebied_Duiding?: string
    /** None */
    ID?: number
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** A UUID reference to a gebruikers object */
    Opdrachtgever?: string
    /** A UUID reference to a gebruikers object */
    Portefeuillehouder_1?: string
    /** A UUID reference to a gebruikers object */
    Portefeuillehouder_2?: string
    /** None */
    Status?: string
    /** None */
    Tags?: string
    /** None */
    Titel?: string
    /** None */
    Toelichting?: string
    /** None */
    Toelichting_Raw?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * An object that shows the changes in the list
 */
export type MaatregelenChangeRefBeleidsmodules = {
    new?: BeleidsmoduleShortInline[]
    removed?: BeleidsmoduleShortInline[]
    same?: BeleidsmoduleShortInline[]
}

/**
 * An object that shows the changes in the list
 */
export type MaatregelenChangeRefBeleidskeuzes = {
    new?: BeleidskeuzeShortInline[]
    removed?: BeleidskeuzeShortInline[]
    same?: BeleidskeuzeShortInline[]
}

/**
 * Schema that defines the structure of maatregelen when looking at changes
 */
export interface MaatregelenChange {
    /** None */
    Aanpassing_Op?: string
    /** None */
    Begin_Geldigheid?: string
    /** None */
    Created_Date?: string
    /** None */
    Effective_Version?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    Gebied_Duiding?: string
    /** None */
    ID?: number
    /** None */
    Latest_Status?: string
    /** None */
    Latest_Version?: string
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An object that shows the changes in the list */
    Ref_Beleidskeuzes?: MaatregelenChangeRefBeleidskeuzes
    /** An object that shows the changes in the list */
    Ref_Beleidsmodules?: MaatregelenChangeRefBeleidsmodules
    /** None */
    Status?: string
    /** None */
    Tags?: string
    /** None */
    Titel?: string
    /** None */
    Toelichting?: string
    /** None */
    Toelichting_Raw?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

export interface ListReference {
    Koppeling_Omschrijving?: string
    UUID?: string
}

/**
 * Schema that defines the structure of Gebruikers when reading
 */
export interface GebruikersRead {
    Gebruikersnaam?: string
    Rol?: string
    Status?: string
    /** The UUID of this gebruiker */
    UUID?: string
}

/**
 * Schema that defines the structure of Gebruikers when reading
 */
export interface GebruikersInline {
    Gebruikersnaam?: string
    Rol?: string
    Status?: string
    /** The UUID of this gebruiker */
    UUID?: string
}

/**
 * Schema that defines how to write beleidsrelaties
 */
export interface BeleidsrelatiesWrite {
    /** None */
    Aanvraag_Datum?: string
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Datum_Akkoord?: string
    /** None */
    Eind_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** A UUID reference to a beleidskeuzes object */
    Naar_Beleidskeuze?: string
    /** None */
    Omschrijving?: string
    /** None */
    Status?: string
    /** A UUID reference to a beleidskeuzes object */
    Van_Beleidskeuze?: string
}

/**
 * Schema that defines the structure of beleidsrelaties when reading
 */
export interface BeleidsrelatiesRead {
    /** None */
    Aanvraag_Datum?: string
    /** None */
    Begin_Geldigheid?: string
    /** An inlined gebruikers object */
    Created_By?: GebruikersInline
    /** None */
    Created_Date?: string
    /** None */
    Datum_Akkoord?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** An inlined gebruikers object */
    Modified_By?: GebruikersInline
    /** None */
    Modified_Date?: string
    /** An inlined beleidskeuzes object */
    Naar_Beleidskeuze?: BeleidskeuzesInline
    /** None */
    Omschrijving?: string
    /** None */
    Status?: string
    /** None */
    UUID?: string
    /** An inlined beleidskeuzes object */
    Van_Beleidskeuze?: BeleidskeuzesInline
}

/**
 * Schema that defines the structure of beleidsrelaties when inlining
 */
export interface BeleidsrelatiesInline {
    /** None */
    Aanvraag_Datum?: string
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Created_Date?: string
    /** None */
    Datum_Akkoord?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Modified_Date?: string
    /** A UUID reference to a beleidskeuzes object */
    Naar_Beleidskeuze?: string
    /** None */
    Omschrijving?: string
    /** None */
    Status?: string
    /** None */
    UUID?: string
    /** A UUID reference to a beleidskeuzes object */
    Van_Beleidskeuze?: string
}

/**
 * Schema that defines the structure of beleidsrelaties when looking at changes
 */
export interface BeleidsrelatiesChange {
    /** None */
    Aanvraag_Datum?: string
    /** None */
    Begin_Geldigheid?: string
    /** None */
    Created_Date?: string
    /** None */
    Datum_Akkoord?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** None */
    Status?: string
    /** None */
    UUID?: string
}

/**
 * Schema that defines how to write beleidsregels
 */
export interface BeleidsregelsWrite {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    Externe_URL?: string
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Omschrijving?: string
    /** None */
    Titel?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of beleidsregels when reading
 */
export interface BeleidsregelsRead {
    /** None */
    Begin_Geldigheid?: string
    /** An inlined gebruikers object */
    Created_By?: GebruikersInline
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    Externe_URL?: string
    /** None */
    ID?: number
    /** An inlined gebruikers object */
    Modified_By?: GebruikersInline
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An list of beleidskeuze-short objects that refer to this object (reverse lookup) */
    Ref_Beleidskeuzes?: BeleidskeuzeShortInline[]
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of beleidsregels when inlining
 */
export interface BeleidsregelsInline {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    Externe_URL?: string
    /** None */
    ID?: number
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * An object that shows the changes in the list
 */
export type BeleidsregelsChangeRefBeleidskeuzes = {
    new?: BeleidskeuzeShortInline[]
    removed?: BeleidskeuzeShortInline[]
    same?: BeleidskeuzeShortInline[]
}

/**
 * Schema that defines the structure of beleidsregels when looking at changes
 */
export interface BeleidsregelsChange {
    /** None */
    Begin_Geldigheid?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    Externe_URL?: string
    /** None */
    ID?: number
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An object that shows the changes in the list */
    Ref_Beleidskeuzes?: BeleidsregelsChangeRefBeleidskeuzes
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines how to write beleidsprestaties
 */
export interface BeleidsprestatiesWrite {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Eind_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Omschrijving?: string
    /** None */
    Titel?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of beleidsprestaties when reading
 */
export interface BeleidsprestatiesRead {
    /** None */
    Begin_Geldigheid?: string
    /** An inlined gebruikers object */
    Created_By?: GebruikersInline
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** An inlined gebruikers object */
    Modified_By?: GebruikersInline
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An list of beleidskeuze-short objects that refer to this object (reverse lookup) */
    Ref_Beleidskeuzes?: BeleidskeuzeShortInline[]
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of beleidsprestaties when inlining
 */
export interface BeleidsprestatiesInline {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * An object that shows the changes in the list
 */
export type BeleidsprestatiesChangeRefBeleidskeuzes = {
    new?: BeleidskeuzeShortInline[]
    removed?: BeleidskeuzeShortInline[]
    same?: BeleidskeuzeShortInline[]
}

/**
 * Schema that defines the structure of beleidsprestaties when looking at changes
 */
export interface BeleidsprestatiesChange {
    /** None */
    Begin_Geldigheid?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An object that shows the changes in the list */
    Ref_Beleidskeuzes?: BeleidsprestatiesChangeRefBeleidskeuzes
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines how to write beleidsmodules
 */
export interface BeleidsmodulesWrite {
    /** None */
    Begin_Geldigheid?: string
    /** An list of references to beleidskeuzes objects */
    Beleidskeuzes?: ListReference[]
    /** None */
    Besluit_Datum?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Eind_Geldigheid?: string
    /** An list of references to maatregelen objects */
    Maatregelen?: ListReference[]
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Titel?: string
}

export type BeleidsmodulesReadMaatregelenItem = {
    Koppeling_Omschrijving?: string
    Object?: MaatregelenInline
}

export type BeleidsmodulesReadBeleidskeuzesItem = {
    Koppeling_Omschrijving?: string
    Object?: BeleidskeuzesInline
}

/**
 * Schema that defines the structure of beleidsmodules when reading
 */
export interface BeleidsmodulesRead {
    /** None */
    Begin_Geldigheid?: string
    /** An list of beleidskeuzes objects */
    Beleidskeuzes?: BeleidsmodulesReadBeleidskeuzesItem[]
    /** None */
    Besluit_Datum?: string
    /** An inlined gebruikers object */
    Created_By?: GebruikersInline
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** An list of maatregelen objects */
    Maatregelen?: BeleidsmodulesReadMaatregelenItem[]
    /** An inlined gebruikers object */
    Modified_By?: GebruikersInline
    /** None */
    Modified_Date?: string
    /** None */
    Titel?: string
    /** None */
    UUID?: string
}

/**
 * Schema that defines the structure of beleidsmodules when inlining
 */
export interface BeleidsmodulesInline {
    /** None */
    Begin_Geldigheid?: string
    /** None */
    Besluit_Datum?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Modified_Date?: string
    /** None */
    Titel?: string
    /** None */
    UUID?: string
}

/**
 * An object that shows the changes in the list
 */
export type BeleidsmodulesChangeMaatregelen = {
    new?: MaatregelenInline[]
    removed?: MaatregelenInline[]
    same?: MaatregelenInline[]
}

/**
 * An object that shows the changes in the list
 */
export type BeleidsmodulesChangeBeleidskeuzes = {
    new?: BeleidskeuzesInline[]
    removed?: BeleidskeuzesInline[]
    same?: BeleidskeuzesInline[]
}

/**
 * Schema that defines the structure of beleidsmodules when looking at changes
 */
export interface BeleidsmodulesChange {
    /** None */
    Begin_Geldigheid?: string
    /** An object that shows the changes in the list */
    Beleidskeuzes?: BeleidsmodulesChangeBeleidskeuzes
    /** None */
    Besluit_Datum?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** An object that shows the changes in the list */
    Maatregelen?: BeleidsmodulesChangeMaatregelen
    /** None */
    Modified_Date?: string
    /** None */
    Titel?: string
    /** None */
    UUID?: string
}

/**
 * Schema that defines how to write beleidsmodule-short
 */
export interface BeleidsmoduleShortWrite {
    /** None */
    Titel?: string
}

/**
 * Schema that defines the structure of beleidsmodule-short when reading
 */
export interface BeleidsmoduleShortRead {
    /** None */
    ID?: number
    /** None */
    Titel?: string
    /** None */
    UUID?: string
}

/**
 * Schema that defines the structure of beleidsmodule-short when inlining
 */
export interface BeleidsmoduleShortInline {
    /** None */
    ID?: number
    /** None */
    Titel?: string
    /** None */
    UUID?: string
}

/**
 * Schema that defines the structure of beleidsmodule-short when looking at changes
 */
export interface BeleidsmoduleShortChange {
    /** None */
    ID?: number
    /** None */
    Titel?: string
    /** None */
    UUID?: string
}

/**
 * Schema that defines how to write beleidskeuzes
 */
export interface BeleidskeuzesWrite {
    /** None */
    Aanleiding?: string
    /** None */
    Aanpassing_Op?: string
    /** None */
    Afweging?: string
    /** An list of references to ambities objects */
    Ambities?: ListReference[]
    /** None */
    Begin_Geldigheid?: string
    /** An list of references to belangen objects */
    Belangen?: ListReference[]
    /** An list of references to beleidsdoelen objects */
    Beleidsdoelen?: ListReference[]
    /** An list of references to beleidskeuze-short objects */
    Beleidskeuzes?: ListReference[]
    /** An list of references to beleidsprestaties objects */
    Beleidsprestaties?: ListReference[]
    /** An list of references to beleidsregels objects */
    Beleidsregels?: ListReference[]
    /** None */
    Besluitnummer?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** A UUID reference to a gebruikers object */
    Eigenaar_1?: string
    /** A UUID reference to a gebruikers object */
    Eigenaar_2?: string
    /** None */
    Eind_Geldigheid?: string
    /** An list of references to maatregelen objects */
    Maatregelen?: ListReference[]
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Omschrijving_Keuze?: string
    /** None */
    Omschrijving_Werking?: string
    /** A UUID reference to a gebruikers object */
    Opdrachtgever?: string
    /** A UUID reference to a gebruikers object */
    Portefeuillehouder_1?: string
    /** A UUID reference to a gebruikers object */
    Portefeuillehouder_2?: string
    /** None */
    Provinciaal_Belang?: string
    /** None */
    Status?: string
    /** None */
    Tags?: string
    /** An list of references to themas objects */
    Themas?: ListReference[]
    /** None */
    Titel?: string
    /** An list of references to verordeningen objects */
    Verordeningen?: ListReference[]
    /** None */
    Weblink?: string
    /** An list of references to werkingsgebieden objects */
    Werkingsgebieden?: ListReference[]
}

export type BeleidskeuzesReadWerkingsgebiedenItem = {
    Koppeling_Omschrijving?: string
    Object?: WerkingsgebiedenInline
}

export type BeleidskeuzesReadVerordeningenItem = {
    Koppeling_Omschrijving?: string
    Object?: VerordeningenInline
}

export type BeleidskeuzesReadThemasItem = {
    Koppeling_Omschrijving?: string
    Object?: ThemasInline
}

export type BeleidskeuzesReadMaatregelenItem = {
    Koppeling_Omschrijving?: string
    Object?: MaatregelenInline
}

export type BeleidskeuzesReadBeleidsregelsItem = {
    Koppeling_Omschrijving?: string
    Object?: BeleidsregelsInline
}

export type BeleidskeuzesReadBeleidsprestatiesItem = {
    Koppeling_Omschrijving?: string
    Object?: BeleidsprestatiesInline
}

export type BeleidskeuzesReadBeleidsdoelenItem = {
    Koppeling_Omschrijving?: string
    Object?: BeleidsdoelenInline
}

export type BeleidskeuzesReadBelangenItem = {
    Koppeling_Omschrijving?: string
    Object?: BelangenInline
}

export type BeleidskeuzesReadAmbitiesItem = {
    Koppeling_Omschrijving?: string
    Object?: AmbitiesInline
}

/**
 * Schema that defines the structure of beleidskeuzes when reading
 */
export interface BeleidskeuzesRead {
    /** None */
    Aanleiding?: string
    /** None */
    Aanpassing_Op?: string
    /** None */
    Afweging?: string
    /** An list of ambities objects */
    Ambities?: BeleidskeuzesReadAmbitiesItem[]
    /** None */
    Begin_Geldigheid?: string
    /** An list of belangen objects */
    Belangen?: BeleidskeuzesReadBelangenItem[]
    /** An list of beleidsdoelen objects */
    Beleidsdoelen?: BeleidskeuzesReadBeleidsdoelenItem[]
    /** An list of beleidskeuze-short objects */
    Beleidskeuzes?: BeleidskeuzesReadBeleidskeuzesItem[]
    /** An list of beleidsprestaties objects */
    Beleidsprestaties?: BeleidskeuzesReadBeleidsprestatiesItem[]
    /** An list of beleidsregels objects */
    Beleidsregels?: BeleidskeuzesReadBeleidsregelsItem[]
    /** None */
    Besluitnummer?: string
    /** An inlined gebruikers object */
    Created_By?: GebruikersInline
    /** None */
    Created_Date?: string
    /** None */
    Effective_Version?: string
    /** An inlined gebruikers object */
    Eigenaar_1?: GebruikersInline
    /** An inlined gebruikers object */
    Eigenaar_2?: GebruikersInline
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** None */
    Latest_Status?: string
    /** None */
    Latest_Version?: string
    /** An list of maatregelen objects */
    Maatregelen?: BeleidskeuzesReadMaatregelenItem[]
    /** An inlined gebruikers object */
    Modified_By?: GebruikersInline
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving_Keuze?: string
    /** None */
    Omschrijving_Werking?: string
    /** An inlined gebruikers object */
    Opdrachtgever?: GebruikersInline
    /** An inlined gebruikers object */
    Portefeuillehouder_1?: GebruikersInline
    /** An inlined gebruikers object */
    Portefeuillehouder_2?: GebruikersInline
    /** None */
    Provinciaal_Belang?: string
    /** An list of beleidsmodule-short objects that refer to this object (reverse lookup) */
    Ref_Beleidsmodules?: BeleidsmoduleShortInline[]
    /** None */
    Status?: string
    /** None */
    Tags?: string
    /** An list of themas objects */
    Themas?: BeleidskeuzesReadThemasItem[]
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** An list of verordeningen objects */
    Verordeningen?: BeleidskeuzesReadVerordeningenItem[]
    /** None */
    Weblink?: string
    /** An list of werkingsgebieden objects */
    Werkingsgebieden?: BeleidskeuzesReadWerkingsgebiedenItem[]
}

/**
 * Schema that defines the structure of beleidskeuzes when inlining
 */
export interface BeleidskeuzesInline {
    /** None */
    Aanleiding?: string
    /** None */
    Aanpassing_Op?: string
    /** None */
    Afweging?: string
    /** None */
    Begin_Geldigheid?: string
    /** None */
    Besluitnummer?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Created_Date?: string
    /** A UUID reference to a gebruikers object */
    Eigenaar_1?: string
    /** A UUID reference to a gebruikers object */
    Eigenaar_2?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving_Keuze?: string
    /** None */
    Omschrijving_Werking?: string
    /** A UUID reference to a gebruikers object */
    Opdrachtgever?: string
    /** A UUID reference to a gebruikers object */
    Portefeuillehouder_1?: string
    /** A UUID reference to a gebruikers object */
    Portefeuillehouder_2?: string
    /** None */
    Provinciaal_Belang?: string
    /** None */
    Status?: string
    /** None */
    Tags?: string
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * An object that shows the changes in the list
 */
export type BeleidskeuzesChangeWerkingsgebieden = {
    new?: WerkingsgebiedenInline[]
    removed?: WerkingsgebiedenInline[]
    same?: WerkingsgebiedenInline[]
}

/**
 * An object that shows the changes in the list
 */
export type BeleidskeuzesChangeVerordeningen = {
    new?: VerordeningenInline[]
    removed?: VerordeningenInline[]
    same?: VerordeningenInline[]
}

/**
 * An object that shows the changes in the list
 */
export type BeleidskeuzesChangeThemas = {
    new?: ThemasInline[]
    removed?: ThemasInline[]
    same?: ThemasInline[]
}

/**
 * An object that shows the changes in the list
 */
export type BeleidskeuzesChangeRefBeleidsmodules = {
    new?: BeleidsmoduleShortInline[]
    removed?: BeleidsmoduleShortInline[]
    same?: BeleidsmoduleShortInline[]
}

/**
 * An object that shows the changes in the list
 */
export type BeleidskeuzesChangeMaatregelen = {
    new?: MaatregelenInline[]
    removed?: MaatregelenInline[]
    same?: MaatregelenInline[]
}

/**
 * An object that shows the changes in the list
 */
export type BeleidskeuzesChangeBeleidsregels = {
    new?: BeleidsregelsInline[]
    removed?: BeleidsregelsInline[]
    same?: BeleidsregelsInline[]
}

/**
 * An object that shows the changes in the list
 */
export type BeleidskeuzesChangeBeleidsprestaties = {
    new?: BeleidsprestatiesInline[]
    removed?: BeleidsprestatiesInline[]
    same?: BeleidsprestatiesInline[]
}

/**
 * An object that shows the changes in the list
 */
export type BeleidskeuzesChangeBeleidsdoelen = {
    new?: BeleidsdoelenInline[]
    removed?: BeleidsdoelenInline[]
    same?: BeleidsdoelenInline[]
}

/**
 * An object that shows the changes in the list
 */
export type BeleidskeuzesChangeBelangen = {
    new?: BelangenInline[]
    removed?: BelangenInline[]
    same?: BelangenInline[]
}

/**
 * An object that shows the changes in the list
 */
export type BeleidskeuzesChangeAmbities = {
    new?: AmbitiesInline[]
    removed?: AmbitiesInline[]
    same?: AmbitiesInline[]
}

/**
 * Schema that defines the structure of beleidskeuzes when looking at changes
 */
export interface BeleidskeuzesChange {
    /** None */
    Aanleiding?: string
    /** None */
    Aanpassing_Op?: string
    /** None */
    Afweging?: string
    /** An object that shows the changes in the list */
    Ambities?: BeleidskeuzesChangeAmbities
    /** None */
    Begin_Geldigheid?: string
    /** An object that shows the changes in the list */
    Belangen?: BeleidskeuzesChangeBelangen
    /** An object that shows the changes in the list */
    Beleidsdoelen?: BeleidskeuzesChangeBeleidsdoelen
    /** An object that shows the changes in the list */
    Beleidskeuzes?: BeleidskeuzesChangeBeleidskeuzes
    /** An object that shows the changes in the list */
    Beleidsprestaties?: BeleidskeuzesChangeBeleidsprestaties
    /** An object that shows the changes in the list */
    Beleidsregels?: BeleidskeuzesChangeBeleidsregels
    /** None */
    Besluitnummer?: string
    /** None */
    Created_Date?: string
    /** None */
    Effective_Version?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** None */
    Latest_Status?: string
    /** None */
    Latest_Version?: string
    /** An object that shows the changes in the list */
    Maatregelen?: BeleidskeuzesChangeMaatregelen
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving_Keuze?: string
    /** None */
    Omschrijving_Werking?: string
    /** None */
    Provinciaal_Belang?: string
    /** An object that shows the changes in the list */
    Ref_Beleidsmodules?: BeleidskeuzesChangeRefBeleidsmodules
    /** None */
    Status?: string
    /** None */
    Tags?: string
    /** An object that shows the changes in the list */
    Themas?: BeleidskeuzesChangeThemas
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** An object that shows the changes in the list */
    Verordeningen?: BeleidskeuzesChangeVerordeningen
    /** None */
    Weblink?: string
    /** An object that shows the changes in the list */
    Werkingsgebieden?: BeleidskeuzesChangeWerkingsgebieden
}

/**
 * Schema that defines how to write beleidskeuze-short
 */
export interface BeleidskeuzeShortWrite {
    /** None */
    ID?: number
    /** None */
    Titel?: string
    /** None */
    UUID?: string
}

/**
 * Schema that defines the structure of beleidskeuze-short when reading
 */
export interface BeleidskeuzeShortRead {
    /** None */
    ID?: number
    /** None */
    Titel?: string
    /** None */
    UUID?: string
}

/**
 * Schema that defines the structure of beleidskeuze-short when inlining
 */
export interface BeleidskeuzeShortInline {
    /** None */
    ID?: number
    /** None */
    Titel?: string
    /** None */
    UUID?: string
}

export type BeleidskeuzesReadBeleidskeuzesItem = {
    Koppeling_Omschrijving?: string
    Object?: BeleidskeuzeShortInline
}

/**
 * An object that shows the changes in the list
 */
export type BeleidskeuzesChangeBeleidskeuzes = {
    new?: BeleidskeuzeShortInline[]
    removed?: BeleidskeuzeShortInline[]
    same?: BeleidskeuzeShortInline[]
}

/**
 * Schema that defines the structure of beleidskeuze-short when looking at changes
 */
export interface BeleidskeuzeShortChange {
    /** None */
    ID?: number
    /** None */
    Titel?: string
    /** None */
    UUID?: string
}

/**
 * Schema that defines how to write beleidsdoelen
 */
export interface BeleidsdoelenWrite {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Eind_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Omschrijving?: string
    /** None */
    Titel?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of beleidsdoelen when reading
 */
export interface BeleidsdoelenRead {
    /** None */
    Begin_Geldigheid?: string
    /** An inlined gebruikers object */
    Created_By?: GebruikersInline
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** An inlined gebruikers object */
    Modified_By?: GebruikersInline
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An list of beleidskeuze-short objects that refer to this object (reverse lookup) */
    Ref_Beleidskeuzes?: BeleidskeuzeShortInline[]
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of beleidsdoelen when inlining
 */
export interface BeleidsdoelenInline {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * An object that shows the changes in the list
 */
export type BeleidsdoelenChangeRefBeleidskeuzes = {
    new?: BeleidskeuzeShortInline[]
    removed?: BeleidskeuzeShortInline[]
    same?: BeleidskeuzeShortInline[]
}

/**
 * Schema that defines the structure of beleidsdoelen when looking at changes
 */
export interface BeleidsdoelenChange {
    /** None */
    Begin_Geldigheid?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An object that shows the changes in the list */
    Ref_Beleidskeuzes?: BeleidsdoelenChangeRefBeleidskeuzes
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines how to write belangen
 */
export interface BelangenWrite {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Eind_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Omschrijving?: string
    /** None */
    Titel?: string
    /** None */
    Type?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of belangen when reading
 */
export interface BelangenRead {
    /** None */
    Begin_Geldigheid?: string
    /** An inlined gebruikers object */
    Created_By?: GebruikersInline
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** An inlined gebruikers object */
    Modified_By?: GebruikersInline
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An list of beleidskeuze-short objects that refer to this object (reverse lookup) */
    Ref_Beleidskeuzes?: BeleidskeuzeShortInline[]
    /** None */
    Titel?: string
    /** None */
    Type?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of belangen when inlining
 */
export interface BelangenInline {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** None */
    Titel?: string
    /** None */
    Type?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * An object that shows the changes in the list
 */
export type BelangenChangeRefBeleidskeuzes = {
    new?: BeleidskeuzeShortInline[]
    removed?: BeleidskeuzeShortInline[]
    same?: BeleidskeuzeShortInline[]
}

/**
 * Schema that defines the structure of belangen when looking at changes
 */
export interface BelangenChange {
    /** None */
    Begin_Geldigheid?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An object that shows the changes in the list */
    Ref_Beleidskeuzes?: BelangenChangeRefBeleidskeuzes
    /** None */
    Titel?: string
    /** None */
    Type?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines how to write ambities
 */
export interface AmbitiesWrite {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Eind_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Omschrijving?: string
    /** None */
    Titel?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of ambities when reading
 */
export interface AmbitiesRead {
    /** None */
    Begin_Geldigheid?: string
    /** An inlined gebruikers object */
    Created_By?: GebruikersInline
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** An inlined gebruikers object */
    Modified_By?: GebruikersInline
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An list of beleidskeuze-short objects that refer to this object (reverse lookup) */
    Ref_Beleidskeuzes?: BeleidskeuzeShortInline[]
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * Schema that defines the structure of ambities when inlining
 */
export interface AmbitiesInline {
    /** None */
    Begin_Geldigheid?: string
    /** A UUID reference to a gebruikers object */
    Created_By?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** A UUID reference to a gebruikers object */
    Modified_By?: string
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}

/**
 * An object that shows the changes in the list
 */
export type AmbitiesChangeRefBeleidskeuzes = {
    new?: BeleidskeuzeShortInline[]
    removed?: BeleidskeuzeShortInline[]
    same?: BeleidskeuzeShortInline[]
}

/**
 * Schema that defines the structure of ambities when looking at changes
 */
export interface AmbitiesChange {
    /** None */
    Begin_Geldigheid?: string
    /** None */
    Created_Date?: string
    /** None */
    Eind_Geldigheid?: string
    /** None */
    ID?: number
    /** None */
    Modified_Date?: string
    /** None */
    Omschrijving?: string
    /** An object that shows the changes in the list */
    Ref_Beleidskeuzes?: AmbitiesChangeRefBeleidskeuzes
    /** None */
    Titel?: string
    /** None */
    UUID?: string
    /** None */
    Weblink?: string
}
