/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Omgevingsbeleid API
 * 
        This API serves all the object that make up the policies 
        of a provincial government. 
        
 * OpenAPI spec version: 3.0-alpha
 */
export type PasswordResetPostParams = { password: string; new_password: string }

export type ModulesGetParams = { only_mine?: boolean; only_active?: boolean }

export type SearchGetParams = { query: string; offset?: number; limit?: number }

export type ModulesModuleIdObjectMaatregelLineageIdGetParams = {
    all_filters?: string
    any_filters?: string
    offset?: number
    limit?: number
}

export type MaatregelenValidLineageIdGetParams = {
    all_filters?: string
    any_filters?: string
    offset?: number
    limit?: number
}

export type MaatregelenValidGetParams = {
    all_filters?: string
    any_filters?: string
    offset?: number
    limit?: number
}

export type ModulesModuleIdObjectBeleidskeuzeLineageIdGetParams = {
    all_filters?: string
    any_filters?: string
    offset?: number
    limit?: number
}

export type BeleidskeuzeAcknowledgedRelationsLineageIdGetParams = {
    requested_by_us?: boolean
    acknowledged?: boolean
}

export type BeleidskeuzesValidLineageIdGetParams = {
    all_filters?: string
    any_filters?: string
    offset?: number
    limit?: number
}

export type BeleidskeuzesValidGetParams = {
    all_filters?: string
    any_filters?: string
    offset?: number
    limit?: number
}

export type ModulesModuleIdObjectBeleidsdoelLineageIdGetParams = {
    all_filters?: string
    any_filters?: string
    offset?: number
    limit?: number
}

export type BeleidsdoelenValidLineageIdGetParams = {
    all_filters?: string
    any_filters?: string
    offset?: number
    limit?: number
}

export type BeleidsdoelenValidGetParams = {
    all_filters?: string
    any_filters?: string
    offset?: number
    limit?: number
}

export type ModulesModuleIdObjectAmbitieLineageIdGetParams = {
    all_filters?: string
    any_filters?: string
    offset?: number
    limit?: number
}

export type AmbitiesValidLineageIdGetParams = {
    all_filters?: string
    any_filters?: string
    offset?: number
    limit?: number
}

export type AmbitiesValidGetParams = {
    all_filters?: string
    any_filters?: string
    offset?: number
    limit?: number
}

export interface Werkingsgebied {
    ID: number
    Werkingsgebied_UUID: string
    Created_Date: string
    Modified_Date: string
    Werkingsgebied: string
}

export type ValidationErrorLocItem = string | number

export interface ValidationError {
    loc: ValidationErrorLocItem[]
    msg: string
    type: string
}

export interface UserShort {
    UUID: string
    Rol: string
    Gebruikersnaam: string
}

export interface SearchObject {
    Object_Type?: string
    Object_ID?: number
    UUID: string
    Title?: string
    Description?: string
}

export interface SearchResponse {
    Objects: SearchObject[]
}

export interface ResponseOK {
    message: string
}

export interface RequestAcknowledgedRelation {
    ID: number
    Object_Type: string
    Title: string
    Explanation: string
}

export interface RelationShort {
    ID: number
    Object_Type: string
    Description?: string
}

export interface ObjectSpecifiekeGeldigheid {
    Object_Type: string
    Object_ID: number
    Start_Validity?: string | null
    End_Validity?: string | null
}

export interface NewObjectStaticResponse {
    Object_Type: string
    Object_ID: number
    Code: string
}

/**
 * An enumeration.
 */
export type ModuleStatusCode =
    typeof ModuleStatusCode[keyof typeof ModuleStatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModuleStatusCode = {
    'Niet-Actief': 'Niet-Actief',
    Ontwerp_GS_Concept: 'Ontwerp GS Concept',
    Ontwerp_GS: 'Ontwerp GS',
    Definitief_ontwerp_GS: 'Definitief ontwerp GS',
    Ontwerp_PS_Concept: 'Ontwerp PS Concept',
    Ontwerp_PS: 'Ontwerp PS',
    Definitief_ontwerp_PS: 'Definitief ontwerp PS',
    Vigerend: 'Vigerend',
} as const

export interface ModuleStatus {
    ID: number
    Module_ID: number
    Status: string
    Created_Date: string
    Created_By_UUID: string
}

export type ModuleSnapshotObjectsItem = { [key: string]: any }

export interface ModuleSnapshot {
    Objects: ModuleSnapshotObjectsItem[]
}

export interface ModulePatchStatus {
    Status: ModuleStatusCode
}

export interface ModuleObjectShort {
    Module_ID: number
    Object_Type: string
    Object_ID: number
    Code: string
    UUID: string
    Modified_Date: string
    Title: string
    Owner_1_UUID?: string
    Owner_2_UUID?: string
    Action: string
    Original_Adjust_On?: string
}

export interface ModuleOverview {
    Module: Module
    StatusHistory: ModuleStatus[]
    Objects: ModuleObjectShort[]
}

export interface ModuleObjectContext {
    Module_ID: number
    Object_Type: string
    Object_ID: number
    Code: string
    Created_Date: string
    Modified_Date: string
    Created_By_UUID: string
    Modified_By_UUID: string
    Action: string
    Explanation: string
    Conclusion: string
}

/**
 * An enumeration.
 */
export type ModuleObjectAction =
    typeof ModuleObjectAction[keyof typeof ModuleObjectAction]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModuleObjectAction = {
    Edit: 'Edit',
    Terminate: 'Terminate',
} as const

export type ModuleEditObjectContextAction = ModuleObjectAction | null

export interface ModuleEditObjectContext {
    Action?: ModuleEditObjectContextAction
    Explanation?: string | null
    Conclusion?: string | null
}

export interface ModuleEdit {
    Temporary_Locked?: boolean | null
    Title?: string | null
    Description?: string | null
    Module_Manager_1_UUID?: string | null
    Module_Manager_2_UUID?: string | null
}

export interface ModuleCreatedResponse {
    Module_ID: number
}

export interface ModuleCreate {
    Title: string
    Description: string
    Module_Manager_1_UUID: string
    Module_Manager_2_UUID?: string | null
}

export interface ModuleAddNewObject {
    Object_Type: string
    Title: string
    Owner_1_UUID: string
    Owner_2_UUID?: string | null
    Client_1_UUID?: string | null
    Explanation: string
    Conclusion: string
}

export interface ModuleAddExistingObject {
    Object_UUID: string
    Action: ModuleObjectAction
    Explanation: string
    Conclusion: string
}

export interface Module {
    Module_ID: number
    Created_Date: string
    Modified_Date: string
    Created_By_UUID: string
    Modified_By_UUID: string
    Activated: boolean
    Closed: boolean
    Successful: boolean
    Temporary_Locked: boolean
    Title: string
    Description: string
    Module_Manager_1_UUID: string
    Module_Manager_2_UUID?: string | null
    Start_Validity?: string | null
    End_Validity?: string | null
    Status?: ModuleStatus
}

export interface MaatregelUUID {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
}

export interface MaatregelStaticPatch {
    /** description is not yet inherited */
    Owner_1_UUID?: string | null
    /** description is not yet inherited */
    Owner_2_UUID?: string | null
    /** description is not yet inherited */
    Portfolio_Holder_1_UUID?: string | null
    /** description is not yet inherited */
    Portfolio_Holder_2_UUID?: string | null
    /** description is not yet inherited */
    Client_1_UUID?: string | null
}

export interface MaatregelPatch {
    /** description is not yet inherited */
    Title?: string | null
    /** description is not yet inherited */
    Description?: string | null
    /** description is not yet inherited */
    Explanation?: string | null
    /** description is not yet inherited */
    Explanation_Raw?: string | null
    /** description is not yet inherited */
    Weblink?: string | null
    /** description is not yet inherited */
    Gebied_Duiding?: string | null
    /** description is not yet inherited */
    Gebied_UUID?: string | null
    /** description is not yet inherited */
    Tags?: string | null
}

export interface MaatregelGet {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
    /** description is not yet inherited */
    Adjust_On?: string | null
    /** description is not yet inherited */
    Created_Date?: string
    /** description is not yet inherited */
    Modified_Date?: string
    /** description is not yet inherited */
    Start_Validity?: string | null
    /** description is not yet inherited */
    End_Validity?: string | null
    /** description is not yet inherited */
    Title?: string
    /** description is not yet inherited */
    Description?: string
    /** description is not yet inherited */
    Explanation?: string
    /** description is not yet inherited */
    Explanation_Raw?: string
    /** description is not yet inherited */
    Weblink?: string
    /** description is not yet inherited */
    Gebied_Duiding?: string
    /** description is not yet inherited */
    Tags?: string
    /** description is not yet inherited */
    Owner_1_UUID?: string | null
    Created_By?: UserShort
    Modified_By?: UserShort
    Beleidsdoelen?: BeleidsdoelShort[]
    Gebied?: Werkingsgebied
}

export interface MaatregelBasic {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
    /** description is not yet inherited */
    Adjust_On?: string | null
    /** description is not yet inherited */
    Created_Date?: string
    /** description is not yet inherited */
    Modified_Date?: string
    /** description is not yet inherited */
    Start_Validity?: string | null
    /** description is not yet inherited */
    End_Validity?: string | null
    /** description is not yet inherited */
    Title?: string
    /** description is not yet inherited */
    Description?: string
    /** description is not yet inherited */
    Explanation?: string
    /** description is not yet inherited */
    Explanation_Raw?: string
    /** description is not yet inherited */
    Weblink?: string
    /** description is not yet inherited */
    Gebied_Duiding?: string
    /** description is not yet inherited */
    Tags?: string
    Created_By?: UserShort
    Modified_By?: UserShort
}

export interface HTTPValidationError {
    detail?: ValidationError[]
}

export interface EditAcknowledgedRelation {
    ID: number
    Object_Type: string
    Title?: string | null
    Explanation?: string | null
    Acknowledged?: boolean | null
}

export interface CompleteModule {
    ObjectSpecifiekeGeldigheden?: ObjectSpecifiekeGeldigheid[]
}

export interface BodyFastapiHandlerLoginAccessTokenPost {
    grant_type?: string
    username: string
    password: string
    scope?: string
    client_id?: string
    client_secret?: string
}

export interface BeleidskeuzeUUID {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
}

export interface BeleidskeuzeStaticPatch {
    /** description is not yet inherited */
    Owner_1_UUID?: string | null
    /** description is not yet inherited */
    Owner_2_UUID?: string | null
    /** description is not yet inherited */
    Portfolio_Holder_1_UUID?: string | null
    /** description is not yet inherited */
    Portfolio_Holder_2_UUID?: string | null
    /** description is not yet inherited */
    Client_1_UUID?: string | null
}

export interface BeleidskeuzeShort {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
    /** description is not yet inherited */
    Title?: string
}

export interface BeleidskeuzePatch {
    /** description is not yet inherited */
    Title?: string | null
    /** description is not yet inherited */
    Description_Choice?: string | null
    /** description is not yet inherited */
    Description_Operation?: string | null
    /** description is not yet inherited */
    Provincial_Interest?: string | null
    /** description is not yet inherited */
    Cause?: string | null
    /** description is not yet inherited */
    Decision_Number?: string | null
    /** description is not yet inherited */
    Tags?: string | null
    /** description is not yet inherited */
    Weblink?: string | null
}

export interface BeleidskeuzeGet {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
    /** description is not yet inherited */
    Adjust_On?: string | null
    /** description is not yet inherited */
    Created_Date?: string
    /** description is not yet inherited */
    Modified_Date?: string
    /** description is not yet inherited */
    Start_Validity?: string | null
    /** description is not yet inherited */
    End_Validity?: string | null
    /** description is not yet inherited */
    Title?: string
    /** description is not yet inherited */
    Description_Choice?: string
    /** description is not yet inherited */
    Description_Operation?: string
    /** description is not yet inherited */
    Provincial_Interest?: string
    /** description is not yet inherited */
    Cause?: string
    /** description is not yet inherited */
    Decision_Number?: string
    /** description is not yet inherited */
    Tags?: string
    /** description is not yet inherited */
    Weblink?: string
    Created_By?: UserShort
    Modified_By?: UserShort
    Owner_1?: UserShort
    Owner_2?: UserShort
    Portfolio_Holder_1?: UserShort
    Portfolio_Holder_2?: UserShort
    Client_1?: UserShort
    Beleidsdoelen?: BeleidsdoelShort[]
}

export interface BeleidskeuzeBasic {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
    /** description is not yet inherited */
    Adjust_On?: string | null
    /** description is not yet inherited */
    Created_Date?: string
    /** description is not yet inherited */
    Modified_Date?: string
    /** description is not yet inherited */
    Start_Validity?: string | null
    /** description is not yet inherited */
    End_Validity?: string | null
    /** description is not yet inherited */
    Title?: string
    /** description is not yet inherited */
    Description_Choice?: string
    /** description is not yet inherited */
    Description_Operation?: string
    /** description is not yet inherited */
    Provincial_Interest?: string
    /** description is not yet inherited */
    Cause?: string
    /** description is not yet inherited */
    Decision_Number?: string
    /** description is not yet inherited */
    Tags?: string
    /** description is not yet inherited */
    Weblink?: string
    Created_By?: UserShort
    Modified_By?: UserShort
}

export interface BeleidsdoelUUID {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
}

export interface BeleidsdoelStaticPatch {
    /** description is not yet inherited */
    Owner_1_UUID?: string | null
    /** description is not yet inherited */
    Owner_2_UUID?: string | null
}

export interface BeleidsdoelShort {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
    /** description is not yet inherited */
    Title?: string
    /** description is not yet inherited */
    Description?: string
}

export interface BeleidsdoelPatch {
    /** description is not yet inherited */
    Title?: string | null
    /** description is not yet inherited */
    Description?: string | null
    /** description is not yet inherited */
    Weblink?: string | null
}

export interface BeleidsdoelGet {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
    /** description is not yet inherited */
    Adjust_On?: string | null
    /** description is not yet inherited */
    Created_Date?: string
    /** description is not yet inherited */
    Modified_Date?: string
    /** description is not yet inherited */
    Title?: string
    /** description is not yet inherited */
    Description?: string
    /** description is not yet inherited */
    Weblink?: string
    /** description is not yet inherited */
    Start_Validity?: string | null
    /** description is not yet inherited */
    End_Validity?: string | null
    Created_By?: UserShort
    Modified_By?: UserShort
    Ambities?: AmbitieShort[]
    Beleidskeuzes?: BeleidskeuzeShort[]
}

export interface BeleidsdoelBasic {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
    /** description is not yet inherited */
    Adjust_On?: string | null
    /** description is not yet inherited */
    Created_Date?: string
    /** description is not yet inherited */
    Modified_Date?: string
    /** description is not yet inherited */
    Title?: string
    /** description is not yet inherited */
    Description?: string
    /** description is not yet inherited */
    Weblink?: string
    Created_By?: UserShort
    Modified_By?: UserShort
}

export interface AuthToken {
    access_token: string
    token_type: string
    identifier: UserShort
}

export interface AmbitieUUID {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
}

export interface AmbitieStaticPost {
    /** description is not yet inherited */
    Owner_1_UUID?: string | null
    /** description is not yet inherited */
    Owner_2_UUID?: string | null
}

export interface AmbitieShort {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
    /** description is not yet inherited */
    Title?: string
}

export interface AmbitiePatch {
    /** description is not yet inherited */
    Title?: string | null
    /** description is not yet inherited */
    Description?: string | null
    /** description is not yet inherited */
    Weblink?: string | null
}

export interface AmbitieGet {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
    /** description is not yet inherited */
    Adjust_On?: string | null
    /** description is not yet inherited */
    Created_Date?: string
    /** description is not yet inherited */
    Modified_Date?: string
    /** description is not yet inherited */
    Title?: string
    /** description is not yet inherited */
    Description?: string
    /** description is not yet inherited */
    Weblink?: string
    /** description is not yet inherited */
    Start_Validity?: string | null
    /** description is not yet inherited */
    End_Validity?: string | null
    Created_By?: UserShort
    Modified_By?: UserShort
    Beleidsdoelen?: BeleidsdoelShort[]
}

export interface AmbitieBasic {
    /** description is not yet inherited */
    Object_ID?: number
    /** description is not yet inherited */
    UUID?: string
    /** description is not yet inherited */
    Adjust_On?: string | null
    /** description is not yet inherited */
    Created_Date?: string
    /** description is not yet inherited */
    Modified_Date?: string
    /** description is not yet inherited */
    Title?: string
    /** description is not yet inherited */
    Weblink?: string
    Created_By?: UserShort
    Modified_By?: UserShort
}

export interface AcknowledgedRelationSide {
    ID: number
    Object_Type: string
    Acknowledged?: boolean
    Acknowledged_Date?: string
    Acknowledged_By_UUID?: string
    Title?: string
    Explanation?: string
}

export interface AcknowledgedRelation {
    Side_A: AcknowledgedRelationSide
    Side_B: AcknowledgedRelationSide
    Requested_By_Code: string
    Created_Date: string
    Created_By_UUID: string
    Modified_Date: string
    Modified_By_UUID: string
}
