/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Omgevingsbeleid API
 *
 *         This API serves all the object that make up the policies
 *         of a provincial government.
 *
 * OpenAPI spec version: 5.0.0
 */
export interface AOJCreate {
    /** @minLength 3 */
    Administrative_Borders_ID: string
    /** @minLength 3 */
    Administrative_Borders_Domain: string
    Administrative_Borders_Date: string
}

export interface AOJCreatedResponse {
    UUID: string
}

export interface AbortResponse {
    new_state_uuid: string
}

export interface AcknowledgedRelationSide {
    Object_ID: number
    Object_Type: string
    Explanation?: string | null
    Acknowledged?: string | null
    Acknowledged_By_UUID?: string | null
    Title?: string | null
}

export interface AcknowledgedRelation {
    Side_A: AcknowledgedRelationSide
    Side_B: AcknowledgedRelationSide
    Version: number
    Requested_By_Code: string
    Created_Date: string
    Created_By_UUID: string
    Modified_Date: string
    Modified_By_UUID: string
    Denied?: string | null
    Deleted_At?: string | null
}

export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType]

export const DocumentType = {
    omgevingsvisie: 'omgevingsvisie',
    programma: 'programma',
} as const

export interface ActCreate {
    Environment_UUID: string
    Document_Type: DocumentType
    Title: string
    Work_Other?: string | null
}

export interface ActCreatedResponse {
    UUID: string
}

export interface ActMetadata {
    Official_Title?: string
    Quote_Title?: string
    Subjects?: string[]
    Jurisdictions?: string[]
}

export interface ActEdit {
    Title?: string | null
    Metadata?: ActMetadata | null
}

export interface ActiveModuleObject {
    Module_ID?: number | null
    UUID: string
    Modified_Date: string
    Title: string
}

export interface ModuleStatus {
    ID: number
    Module_ID: number
    Status: string
    Created_Date: string
    Created_By_UUID: string
}

export interface UserShort {
    UUID: string
}

export interface ModuleShort {
    Module_ID: number
    Closed: boolean
    Title: string
    Description: string
    Status?: ModuleStatus | null
    Module_Manager_1?: UserShort | null
    Module_Manager_2?: UserShort | null
}

export type ModuleObjectActionFull =
    (typeof ModuleObjectActionFull)[keyof typeof ModuleObjectActionFull]

export const ModuleObjectActionFull = {
    Create: 'Create',
    Edit: 'Edit',
    Terminate: 'Terminate',
} as const

export interface ActiveModuleObjectsResponse {
    Module: ModuleShort
    Module_Object: ActiveModuleObject
    Action: ModuleObjectActionFull
}

export interface NextObjectVersion {
    UUID: string
    Title: string
    Start_Validity: string
    End_Validity?: string | null
    Created_Date: string
    Modified_Date: string
    Previous_UUID: string
}

export interface AmbitieBasic {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Next_Version?: NextObjectVersion | null
}

export interface AmbitieExtendedStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface AmbitieExtended {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Themas?: string[]
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    ObjectStatics?: AmbitieExtendedStatics
}

export interface ReadRelationShort {
    Object_ID: number
    Object_Type: string
    Description?: string
}

export interface BeleidsdoelMinimal {
    Object_Type?: string
    Object_ID?: number
    UUID?: string
    Title?: string
}

export interface ReadRelationShortBeleidsdoelMinimal {
    Relation?: ReadRelationShort
    Object?: BeleidsdoelMinimal
}

export interface HierachyReference {
    UUID: string
    Object_Type: string
    Object_ID: number
    Code: string
    Hierarchy_Code: string
    Title?: string | null
}

export interface ObjectStatics {
    Object_Type: string
    Object_ID: number
    Code: string
    Cached_Title: string
}

export type ModuleStatusCode =
    (typeof ModuleStatusCode)[keyof typeof ModuleStatusCode]

export const ModuleStatusCode = {
    Ontwerp_GS_Concept: 'Ontwerp GS Concept',
    Ontwerp_GS: 'Ontwerp GS',
    Ontwerp_PS: 'Ontwerp PS',
    Ter_Inzage: 'Ter Inzage',
    Definitief_ontwerp_GS_Concept: 'Definitief ontwerp GS Concept',
    Definitief_ontwerp_GS: 'Definitief ontwerp GS',
    Definitief_ontwerp_PS: 'Definitief ontwerp PS',
    Vastgesteld: 'Vastgesteld',
} as const

export type PublicModuleStatusCode =
    (typeof PublicModuleStatusCode)[keyof typeof PublicModuleStatusCode]

export const PublicModuleStatusCode = {
    Ter_Inzage: 'Ter Inzage',
    Ontwerp_GS: 'Ontwerp GS',
    Definitief_ontwerp_GS: 'Definitief ontwerp GS',
    Ontwerp_PS: 'Ontwerp PS',
    Definitief_ontwerp_PS: 'Definitief ontwerp PS',
    Vastgesteld: 'Vastgesteld',
} as const

export interface PublicModuleObjectRevision {
    Module_ID: number
    Module_Title: string
    Module_Status: ModuleStatusCode
    Module_Object_UUID: string
    Module_Object_Code: string
    Module_Object_Status: PublicModuleStatusCode
    Action: ModuleObjectActionFull
}

export interface AmbitieFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface AmbitieFull {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Description?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Themas?: string[]
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Beleidsdoelen?: ReadRelationShortBeleidsdoelMinimal[]
    Hierarchy_Children?: HierachyReference[]
    Gebiedsaanwijzingen_Statics?: ObjectStatics[]
    Public_Revisions?: PublicModuleObjectRevision[]
    Next_Version?: NextObjectVersion | null
    ObjectStatics?: AmbitieFullStatics
}

export interface AmbitieMinimal {
    Object_Type?: string
    Object_ID?: number
    UUID?: string
    Title?: string
}

export interface AmbitieStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
    Portfolio_Holder_1_UUID?: string | null
    Portfolio_Holder_2_UUID?: string | null
    Client_1_UUID?: string | null
}

export interface AmbitieStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface AmbitieUUID {
    Object_ID?: number
    UUID?: string
}

export interface AmendmentAppendix {
    Number: string
    Title: string
}

export interface AnnouncementText {
    Title: string | null
    Description: string
}

export interface AnnouncementContent {
    Texts: AnnouncementText[]
}

export interface AnnouncementCreatedResponse {
    UUID: string
}

export interface AnnouncementMetadata {
    Official_Title?: string
    Subjects?: string[]
}

export interface AnnouncementProcedural {
    Procedural_Announcement_Date?: string | null
    Begin_Inspection_Period_Date?: string | null
    End_Inspection_Period_Date?: string | null
}

export interface Appendix {
    Number: string
    Title: string
    Content: string
}

export interface AreaBasic {
    UUID: string
    Created_Date: string
    Created_By_UUID: string
    Source_UUID: string
    Source_Title: string
    Source_Created_Date: string
}

export interface Article {
    Label?: string
    Number: string
    Content: string
}

export interface AttachmentShort {
    ID: number
    File_UUID: string
    Filename: string
    Title: string
    Created_Date: string
    Modified_Date: string
}

export interface UserLoginDetail {
    UUID: string
    Roles: string[]
    Gebruikersnaam: string
}

export interface AuthToken {
    access_token: string
    token_type: string
    identifier: UserLoginDetail
}

export interface BeleidsdoelBasic {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Next_Version?: NextObjectVersion | null
}

export interface BeleidsdoelExtendedStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface BeleidsdoelExtended {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Description?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Hierarchy_Code?: string
    Themas?: string[]
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    ObjectStatics?: BeleidsdoelExtendedStatics
}

export interface HierarchyStatics {
    Object_Type: string
    Object_ID: number
    Code: string
    Cached_Title: string
}

export interface ReadRelationShortAmbitieMinimal {
    Relation?: ReadRelationShort
    Object?: AmbitieMinimal
}

export interface BeleidskeuzeMinimal {
    Object_Type?: string
    Object_ID?: number
    UUID?: string
    Title?: string
}

export interface ReadRelationShortBeleidskeuzeMinimal {
    Relation?: ReadRelationShort
    Object?: BeleidskeuzeMinimal
}

export interface ObjectRelatedFileResponse {
    UUID: string
    Code: string
    File_UUID: string
    Title: string
    Created_Date: string
    Created_By_UUID: string
}

export interface BeleidsdoelFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface BeleidsdoelFull {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Description?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Hierarchy_Code?: string
    Themas?: string[]
    Hierarchy_Statics?: HierarchyStatics | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Ambities?: ReadRelationShortAmbitieMinimal[]
    Beleidskeuzes?: ReadRelationShortBeleidskeuzeMinimal[]
    Hierarchy_Children?: HierachyReference[]
    Gebiedsaanwijzingen_Statics?: ObjectStatics[]
    Public_Revisions?: PublicModuleObjectRevision[]
    Next_Version?: NextObjectVersion | null
    Related_Files?: ObjectRelatedFileResponse[]
    ObjectStatics?: BeleidsdoelFullStatics
}

export interface BeleidsdoelStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
    Portfolio_Holder_1_UUID?: string | null
    Portfolio_Holder_2_UUID?: string | null
    Client_1_UUID?: string | null
}

export interface BeleidsdoelStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface BeleidsdoelUUID {
    Object_ID?: number
    UUID?: string
}

export interface BeleidskeuzeBasic {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Title?: string
    Next_Version?: NextObjectVersion | null
}

export interface BeleidskeuzeExtendedStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface BeleidskeuzeExtended {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Title?: string
    Hierarchy_Code?: string
    Werkingsgebied_Code?: string
    Gebiedengroep_Code?: string | null
    Themas?: string[]
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    ObjectStatics?: BeleidskeuzeExtendedStatics
}

export interface WerkingsgebiedStatics {
    Object_Type: string
    Object_ID: number
    Code: string
    Cached_Title: string
}

export interface WettelijkeTaakMinimal {
    Object_Type?: string
    Object_ID?: number
    Code?: string
    UUID?: string
    Created_Date?: string
    Modified_Date?: string
    Title?: string
}

export interface ReadRelationShortWettelijkeTaakMinimal {
    Relation?: ReadRelationShort
    Object?: WettelijkeTaakMinimal
}

export interface NationaalBelangMinimal {
    Object_Type?: string
    Object_ID?: number
    Code?: string
    UUID?: string
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Weblink?: string
}

export interface ReadRelationShortNationaalBelangMinimal {
    Relation?: ReadRelationShort
    Object?: NationaalBelangMinimal
}

export interface BeleidsregelMinimal {
    Object_Type?: string
    Object_ID?: number
    UUID?: string
    Title?: string
}

export interface ReadRelationShortBeleidsregelMinimal {
    Relation?: ReadRelationShort
    Object?: BeleidsregelMinimal
}

export interface MaatregelMinimal {
    Object_Type?: string
    Object_ID?: number
    UUID?: string
    Title?: string
}

export interface ReadRelationShortMaatregelMinimal {
    Relation?: ReadRelationShort
    Object?: MaatregelMinimal
}

export interface WerkingsgebiedBasic {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Area_UUID?: string | null
    Start_Validity?: string | null
    End_Validity?: string | null
}

export interface BeleidskeuzeFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface BeleidskeuzeFull {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Title?: string
    Description?: string
    Cause?: string
    Provincial_Interest?: string
    Explanation?: string
    Hierarchy_Code?: string
    Werkingsgebied_Code?: string
    Gebiedengroep_Code?: string | null
    Themas?: string[]
    Hierarchy_Statics?: HierarchyStatics | null
    Werkingsgebied_Statics?: WerkingsgebiedStatics | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    WettelijkeTaken?: ReadRelationShortWettelijkeTaakMinimal[]
    NationaleBelangen?: ReadRelationShortNationaalBelangMinimal[]
    Beleidsdoelen?: ReadRelationShortBeleidsdoelMinimal[]
    Beleidsregels?: ReadRelationShortBeleidsregelMinimal[]
    Maatregelen?: ReadRelationShortMaatregelMinimal[]
    Werkingsgebied?: WerkingsgebiedBasic | null
    Hierarchy_Children?: HierachyReference[]
    Gebiedengroep_Static?: ObjectStatics | null
    Gebiedsaanwijzingen_Statics?: ObjectStatics[]
    Public_Revisions?: PublicModuleObjectRevision[]
    Next_Version?: NextObjectVersion | null
    ObjectStatics?: BeleidskeuzeFullStatics
}

export interface BeleidskeuzeStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
    Portfolio_Holder_1_UUID?: string | null
    Portfolio_Holder_2_UUID?: string | null
    Client_1_UUID?: string | null
}

export interface BeleidskeuzeStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface BeleidskeuzeUUID {
    Object_ID?: number
    UUID?: string
}

export interface BeleidsregelBasic {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Weblink?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Next_Version?: NextObjectVersion | null
}

export interface BeleidsregelExtendedStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface BeleidsregelExtended {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Weblink?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    ObjectStatics?: BeleidsregelExtendedStatics
}

export interface BeleidsregelFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface BeleidsregelFull {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Weblink?: string
    Description?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Beleidskeuzes?: ReadRelationShortBeleidskeuzeMinimal[]
    Public_Revisions?: PublicModuleObjectRevision[]
    Next_Version?: NextObjectVersion | null
    ObjectStatics?: BeleidsregelFullStatics
}

export interface BeleidsregelStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
    Portfolio_Holder_1_UUID?: string | null
    Portfolio_Holder_2_UUID?: string | null
    Client_1_UUID?: string | null
}

export interface BeleidsregelStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface BeleidsregelUUID {
    Object_ID?: number
    UUID?: string
}

export interface Motivation {
    Number?: string | null
    Title: string
    Content: string
    Appendices?: Appendix[]
}

export interface BillCompact {
    Preamble?: string
    Closing?: string
    Signed?: string
    Amendment_Article?: string
    Amendment_Appendix?: AmendmentAppendix
    Time_Article?: string
    Custom_Articles?: Article[]
    Appendices?: Appendix[]
    Motivation?: Motivation | null
}

export interface BillMetadata {
    Official_Title?: string
    Quote_Title?: string
    Subjects?: string[]
    Jurisdictions?: string[]
}

export interface BodyAuthenticationPostAuthLoginAccessToken {
    grant_type?: string | null
    username: string
    password: string
    scope?: string
    client_id?: string | null
    client_secret?: string | null
}

export interface BodyObjectRelatedFilesPostObjectRelatedFilesUpload {
    title: string
    ignore_report: boolean
    uploaded_file: Blob
}

export interface BodyPublicationActReportsPostUploadActPackageReport {
    uploaded_files: Blob[]
}

export interface BodyPublicationAnnouncementReportsPostUploadAnnouncementPackageReport {
    uploaded_files: Blob[]
}

export interface BodyPublicationVersionsPostUploadAttachment {
    title: string
    uploaded_file: Blob
    ignore_report: boolean
}

export interface BodyStorageFilePostFilesUpload {
    title: string
    ignore_report: boolean
    uploaded_file: Blob
}

export interface CompleteModule {
    start_validity?: string | null
}

export interface CreateHoofdlijn {
    /**
     * @minLength 3
     * @maxLength 255
     */
    Name: string
    /**
     * @minLength 3
     * @maxLength 255
     */
    Type: string
}

export interface DocumentBasic {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Filename?: string
    File_UUID?: string | null
    Start_Validity?: string | null
    End_Validity?: string | null
    Next_Version?: NextObjectVersion | null
}

export interface DocumentExtendedStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface DocumentExtended {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Filename?: string
    File_UUID?: string | null
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    ObjectStatics?: DocumentExtendedStatics
}

export interface StorageFileBasic {
    UUID: string
    Checksum: string
    Filename: string
    Content_Type: string
    Size: number
    Created_Date: string
    Created_By_UUID: string
}

export interface DocumentFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface DocumentFull {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Filename?: string
    Description?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    File_UUID?: string | null
    File?: StorageFileBasic | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Public_Revisions?: PublicModuleObjectRevision[]
    Next_Version?: NextObjectVersion | null
    ObjectStatics?: DocumentFullStatics
}

export interface DocumentStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
}

export interface DocumentStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface DocumentUUID {
    Object_ID?: number
    UUID?: string
}

export interface EditAcknowledgedRelation {
    Object_ID: number
    Object_Type: string
    Explanation?: string | null
    Acknowledged?: boolean | null
    Denied?: boolean | null
    Deleted?: boolean | null
}

export interface EditHoofdlijn {
    Name?: string | null
    Type?: string | null
}

export interface EditUser {
    Gebruikersnaam?: string | null
    Email?: string | null
    Roles?: string[] | null
    IsActive?: boolean | null
}

export interface EnvironmentCreate {
    /** @minLength 3 */
    Title: string
    Description: string
    Province_ID: string
    Authority_ID: string
    Submitter_ID: string
    Frbr_Country: string
    Frbr_Language: string
    Has_State: boolean
    Can_Validate: boolean
    Can_Publicate: boolean
}

export interface EnvironmentCreatedResponse {
    UUID: string
}

export interface EnvironmentEdit {
    Title?: string | null
    Description?: string | null
    Province_ID?: string | null
    Authority_ID?: string | null
    Submitter_ID?: string | null
    Frbr_Country?: string | null
    Frbr_Language?: string | null
    Is_Active?: boolean | null
    Can_Validate?: boolean | null
    Can_Publicate?: boolean | null
}

export type ErrorDetailsCtx = { [key: string]: unknown }

export interface ErrorDetails {
    type: string
    loc: (number | string)[]
    msg: string
    input: unknown
    ctx?: ErrorDetailsCtx
    url?: string
}

export interface GebiedBasic {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Area_UUID?: string | null
    Start_Validity?: string | null
    End_Validity?: string | null
}

export interface GebiedExtendedStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface GebiedExtended {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Area_UUID?: string | null
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    ObjectStatics?: GebiedExtendedStatics
}

export interface GebiedFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface GebiedFull {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Area_UUID?: string | null
    Start_Validity?: string | null
    End_Validity?: string | null
    Area?: AreaBasic | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Public_Revisions?: PublicModuleObjectRevision[]
    Next_Version?: NextObjectVersion | null
    ObjectStatics?: GebiedFullStatics
}

export interface GebiedStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
}

export interface GebiedStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface GebiedUUID {
    Object_ID?: number
    UUID?: string
}

export interface GebiedengroepBasic {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Source_Title?: string
    Start_Validity?: string | null
    End_Validity?: string | null
}

export interface GebiedengroepExtendedStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface GebiedengroepExtended {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Source_Title?: string
    Source_UUID?: string | null
    Gebieden?: string[]
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    ObjectStatics?: GebiedengroepExtendedStatics
}

export interface GebiedengroepFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface GebiedengroepFull {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Source_Title?: string
    Source_UUID?: string | null
    Description?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Gebieden?: string[]
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Gebieden_Statics?: ObjectStatics[]
    ObjectStatics?: GebiedengroepFullStatics
}

export interface GebiedengroepStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
}

export interface GebiedengroepStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface GebiedengroepUUID {
    Object_ID?: number
    UUID?: string
}

export interface GebiedsaanwijzingType {
    label: string
    term: string
    uri: string
    definitie: string
    bron: string
    domein: string
    deprecated: boolean
}

export interface GebiedsaanwijzingGroep {
    label: string
    titel: string
    uri: string
    omschrijving: string
    toelichting: string
}

export interface GebiedsaanwijzingWaarde {
    label: string
    term: string
    uri: string
    definitie: string
    toelichting: string
    bron: string
    domein: string
    deprecated: boolean
}

export interface Gebiedsaanwijzing {
    aanwijzing_type: GebiedsaanwijzingType
    aanwijzing_groep: GebiedsaanwijzingGroep
    waardes: GebiedsaanwijzingWaarde[]
}

export interface GebiedsaanwijzingBasic {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Start_Validity?: string | null
    End_Validity?: string | null
}

export interface GebiedsaanwijzingExtendedStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface GebiedsaanwijzingExtended {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Ref_Type?: string
    Ref_Group?: string
    Target_Codes?: string[]
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    ObjectStatics?: GebiedsaanwijzingExtendedStatics
}

export interface GebiedsaanwijzingFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface GebiedsaanwijzingFull {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Ref_Type?: string
    Ref_Group?: string
    Target_Codes?: string[]
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Geo_Statics?: ObjectStatics[]
    ObjectStatics?: GebiedsaanwijzingFullStatics
}

export interface GebiedsaanwijzingStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
}

export interface GebiedsaanwijzingStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface GebiedsaanwijzingUUID {
    Object_ID?: number
    UUID?: string
}

export interface GebiedsprogrammaBasic {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Image?: string | null
    Next_Version?: NextObjectVersion | null
}

export interface GebiedsprogrammaExtendedStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface GebiedsprogrammaExtended {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Image?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    ObjectStatics?: GebiedsprogrammaExtendedStatics
}

export interface GebiedsprogrammaFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface GebiedsprogrammaFull {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Description?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Image?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Maatregelen?: ReadRelationShortMaatregelMinimal[]
    Public_Revisions?: PublicModuleObjectRevision[]
    Next_Version?: NextObjectVersion | null
    ObjectStatics?: GebiedsprogrammaFullStatics
}

export interface GebiedsprogrammaMinimal {
    Object_Type?: string
    Object_ID?: number
    UUID?: string
    Title?: string
}

export interface GebiedsprogrammaStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
    Portfolio_Holder_1_UUID?: string | null
    Portfolio_Holder_2_UUID?: string | null
    Client_1_UUID?: string | null
}

export interface GebiedsprogrammaStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface GebiedsprogrammaUUID {
    Object_ID?: number
    UUID?: string
}

export type GraphEdgeType = (typeof GraphEdgeType)[keyof typeof GraphEdgeType]

export const GraphEdgeType = {
    relation: 'relation',
    acknowledged_relation: 'acknowledged_relation',
    hierarchy_code: 'hierarchy_code',
} as const

export interface GraphEdge {
    Vertice_A_Code: string
    Vertice_B_Code: string
    Type: GraphEdgeType
}

export interface GraphVertice {
    UUID: string
    Object_Type: string
    Object_ID: number
    Code: string
    Title: string
}

export interface GraphResponse {
    Vertices: GraphVertice[]
    Edges: GraphEdge[]
}

export type ValidationErrorCtx = { [key: string]: unknown }

export interface ValidationError {
    loc: (string | number)[]
    msg: string
    type: string
    input?: unknown
    ctx?: ValidationErrorCtx
}

export interface HTTPValidationError {
    detail?: ValidationError[]
}

export interface Hoofdlijn {
    UUID: string
    Name: string
    Type: string
}

export interface HoofdlijnCreatedResponse {
    UUID: string
}

export interface InputGeoOnderverdeling {
    UUID: string
    Created_Date: string
    Title: string
    Description: string
    Geometry_Hash: string
}

export interface InputGeoWerkingsgebied {
    UUID: string
    Created_Date: string
    Title: string
    Description: string
}

export interface InputGeoWerkingsgebiedDetailed {
    UUID: string
    Created_Date: string
    Title: string
    Description: string
    Onderverdelingen: InputGeoOnderverdeling[]
}

export type InputGeoWerkingsgebiedenSortColumn =
    (typeof InputGeoWerkingsgebiedenSortColumn)[keyof typeof InputGeoWerkingsgebiedenSortColumn]

export const InputGeoWerkingsgebiedenSortColumn = {
    Title: 'Title',
    Created_Date: 'Created_Date',
} as const

export interface ListAreaDesignationResponse {
    gebiedsaanwijzingen: Gebiedsaanwijzing[]
}

export interface Thema {
    label: string
    term: string
    uri: string
    definitie: string
    toelichting: string
    bron: string
    domein: string
    deprecated: boolean
}

export interface ListThemaResponse {
    themas: Thema[]
}

export interface MaatregelBasic {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Title?: string
    Next_Version?: NextObjectVersion | null
}

export interface MaatregelExtendedStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface MaatregelExtended {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Title?: string
    Hierarchy_Code?: string
    Werkingsgebied_Code?: string
    Gebiedengroep_Code?: string | null
    Themas?: string[]
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    ObjectStatics?: MaatregelExtendedStatics
}

export interface ReadRelationShortGebiedsprogrammaMinimal {
    Relation?: ReadRelationShort
    Object?: GebiedsprogrammaMinimal
}

export interface MaatregelFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface MaatregelFull {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Title?: string
    Description?: string
    Documents?: string[]
    Role?: string
    Effect?: string
    Hierarchy_Code?: string
    Werkingsgebied_Code?: string
    Gebiedengroep_Code?: string | null
    Themas?: string[]
    Hierarchy_Statics?: HierarchyStatics | null
    Werkingsgebied_Statics?: WerkingsgebiedStatics | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Beleidskeuzes?: ReadRelationShortBeleidskeuzeMinimal[]
    Gebiedsprogrammas?: ReadRelationShortGebiedsprogrammaMinimal[]
    Werkingsgebied?: WerkingsgebiedBasic | null
    Documents_Statics?: ObjectStatics[]
    Gebiedengroep_Static?: ObjectStatics | null
    Gebiedsaanwijzingen_Statics?: ObjectStatics[]
    Public_Revisions?: PublicModuleObjectRevision[]
    Next_Version?: NextObjectVersion | null
    ObjectStatics?: MaatregelFullStatics
}

export interface MaatregelStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
    Portfolio_Holder_1_UUID?: string | null
    Portfolio_Holder_2_UUID?: string | null
    Client_1_UUID?: string | null
}

export interface MaatregelStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
    Portfolio_Holder_1?: UserShort | null
    Portfolio_Holder_2?: UserShort | null
    Client_1?: UserShort | null
}

export interface MaatregelUUID {
    Object_ID?: number
    UUID?: string
}

export interface Module {
    Module_ID: number
    Created_Date: string
    Modified_Date: string
    Created_By_UUID: string
    Modified_By_UUID: string
    Activated: boolean
    Closed: boolean
    Successful: boolean
    Temporary_Locked: boolean
    Title: string
    Description: string
    Module_Manager_1_UUID: string
    Module_Manager_2_UUID?: string | null
    Status?: ModuleStatus | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Module_Manager_1?: UserShort | null
    Module_Manager_2?: UserShort | null
}

export type ModuleObjectAction =
    (typeof ModuleObjectAction)[keyof typeof ModuleObjectAction]

export const ModuleObjectAction = {
    Edit: 'Edit',
    Terminate: 'Terminate',
} as const

export interface ModuleAddExistingObject {
    Object_UUID: string
    Action: ModuleObjectAction
    Explanation?: string
    Conclusion?: string
}

export interface ModuleAddNewObject {
    Object_Type: string
    /** @minLength 3 */
    Title: string
    Owner_1_UUID: string
    Owner_2_UUID?: string | null
    Client_1_UUID?: string | null
    Explanation?: string
    Conclusion?: string
}

export interface ModuleCreate {
    /** @minLength 3 */
    Title: string
    /** @minLength 3 */
    Description: string
    Module_Manager_1_UUID: string
    Module_Manager_2_UUID?: string | null
}

export interface ModuleCreatedResponse {
    Module_ID: number
}

export interface ModuleEdit {
    Temporary_Locked?: boolean | null
    Title?: string | null
    Description?: string | null
    Module_Manager_1_UUID?: string | null
    Module_Manager_2_UUID?: string | null
}

export interface ModuleEditObjectContext {
    Action?: ModuleObjectAction | null
    Explanation?: string | null
    Conclusion?: string | null
}

export interface ModuleObjectContext {
    Module_ID: number
    Object_Type: string
    Object_ID: number
    Code: string
    Created_Date: string
    Modified_Date: string
    Action: string
    Explanation: string
    Conclusion: string
    Original_Adjust_On?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
}

export interface ModuleObjectContextShort {
    Action: string
    Original_Adjust_On?: string | null
}

export interface ObjectStaticShort {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
    Portfolio_Holder_1_UUID?: string | null
    Portfolio_Holder_2_UUID?: string | null
    Client_1_UUID?: string | null
}

export interface NationaalBelangBasic {
    Object_Type?: string
    Object_ID?: number
    Code?: string
    UUID?: string
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Weblink?: string
}

export interface ProgrammaAlgemeenBasic {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Next_Version?: NextObjectVersion | null
}

export interface VerplichtProgrammaBasic {
    Object_Type?: string
    Object_ID?: number
    Code?: string
    UUID?: string
    Created_Date?: string
    Modified_Date?: string
    Title?: string
}

export interface VisieAlgemeenBasic {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Next_Version?: NextObjectVersion | null
}

export interface WettelijkeTaakBasic {
    Object_Type?: string
    Object_ID?: number
    Code?: string
    UUID?: string
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Weblink?: string
}

export interface ModuleObjectsResponseUnionAmbitieBasicBeleidsdoelBasicBeleidskeuzeBasicBeleidsregelBasicDocumentBasicGebiedsprogrammaBasicMaatregelBasicNationaalBelangBasicGebiedengroepBasicGebiedBasicGebiedsaanwijzingBasicProgrammaAlgemeenBasicVerplichtProgrammaBasicVisieAlgemeenBasicWerkingsgebiedBasicWettelijkeTaakBasic {
    Module_ID: number
    Module_Latest_Status: string
    Object_Type: string
    ObjectStatics: ObjectStaticShort
    ModuleObjectContext: ModuleObjectContextShort
    Model:
        | AmbitieBasic
        | BeleidsdoelBasic
        | BeleidskeuzeBasic
        | BeleidsregelBasic
        | DocumentBasic
        | GebiedsprogrammaBasic
        | MaatregelBasic
        | NationaalBelangBasic
        | GebiedengroepBasic
        | GebiedBasic
        | GebiedsaanwijzingBasic
        | ProgrammaAlgemeenBasic
        | VerplichtProgrammaBasic
        | VisieAlgemeenBasic
        | WerkingsgebiedBasic
        | WettelijkeTaakBasic
}

export interface ModuleOverviewResponse {
    Module: Module
    StatusHistory: ModuleStatus[]
}

export interface ModulePatchStatus {
    Status: ModuleStatusCode
}

export type ModuleSnapshotObjectsItem = { [key: string]: unknown }

export interface ModuleSnapshot {
    Objects: ModuleSnapshotObjectsItem[]
}

export type ModuleSortColumn =
    (typeof ModuleSortColumn)[keyof typeof ModuleSortColumn]

export const ModuleSortColumn = {
    Module_ID: 'Module_ID',
    Title: 'Title',
    Created_Date: 'Created_Date',
    Modified_Date: 'Modified_Date',
    Activated: 'Activated',
    Closed: 'Closed',
    Successful: 'Successful',
    Temporary_Locked: 'Temporary_Locked',
} as const

export type MutationStrategy =
    (typeof MutationStrategy)[keyof typeof MutationStrategy]

export const MutationStrategy = {
    renvooi: 'renvooi',
    replace: 'replace',
} as const

export interface NationaalBelangCreateStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
}

export interface NationaalBelangCreate {
    Title?: string
    Weblink?: string | null
    ObjectStatics?: NationaalBelangCreateStatics
}

export interface NationaalBelangEdit {
    Title?: string | null
    Weblink?: string | null
}

export interface NationaalBelangFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface NationaalBelangFull {
    Object_Type?: string
    Object_ID?: number
    Code?: string
    UUID?: string
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Weblink?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Beleidskeuzes?: BeleidskeuzeMinimal[]
    ObjectStatics?: NationaalBelangFullStatics
}

export interface NationaalBelangStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
}

export interface NationaalBelangStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface NationaalBelangUUID {
    Object_ID?: number
    UUID?: string
}

export interface NewObjectStaticResponse {
    Object_Type: string
    Object_ID: number
    Code: string
}

export interface ObjectCount {
    object_type: string
    count: number
}

export interface ObjectListAllLatestResponseUnionAmbitieBasicBeleidsdoelBasicBeleidskeuzeBasicBeleidsregelBasicDocumentBasicGebiedsprogrammaBasicMaatregelBasicNationaalBelangBasicGebiedengroepBasicGebiedBasicGebiedsaanwijzingBasicProgrammaAlgemeenBasicVerplichtProgrammaBasicVisieAlgemeenBasicWerkingsgebiedBasicWettelijkeTaakBasic {
    Object_Type: string
    ObjectStatics: ObjectStaticShort
    Model:
        | AmbitieBasic
        | BeleidsdoelBasic
        | BeleidskeuzeBasic
        | BeleidsregelBasic
        | DocumentBasic
        | GebiedsprogrammaBasic
        | MaatregelBasic
        | NationaalBelangBasic
        | GebiedengroepBasic
        | GebiedBasic
        | GebiedsaanwijzingBasic
        | ProgrammaAlgemeenBasic
        | VerplichtProgrammaBasic
        | VisieAlgemeenBasic
        | WerkingsgebiedBasic
        | WettelijkeTaakBasic
}

export type OwnerType = (typeof OwnerType)[keyof typeof OwnerType]

export const OwnerType = {
    All: 'All',
    Mine: 'Mine',
    Others: 'Others',
} as const

export type PackageType = (typeof PackageType)[keyof typeof PackageType]

export const PackageType = {
    validation: 'validation',
    publication: 'publication',
} as const

export interface PackageZipShort {
    UUID: string
    Filename: string
    Latest_Download_Date?: string | null
    Latest_Download_By_UUID?: string | null
}

export interface PagedResponseAmbitieBasic {
    total: number
    offset?: number
    limit?: number
    results: AmbitieBasic[]
}

export interface PagedResponseAmbitieExtended {
    total: number
    offset?: number
    limit?: number
    results: AmbitieExtended[]
}

export interface PagedResponseBeleidsdoelBasic {
    total: number
    offset?: number
    limit?: number
    results: BeleidsdoelBasic[]
}

export interface PagedResponseBeleidsdoelExtended {
    total: number
    offset?: number
    limit?: number
    results: BeleidsdoelExtended[]
}

export interface PagedResponseBeleidskeuzeBasic {
    total: number
    offset?: number
    limit?: number
    results: BeleidskeuzeBasic[]
}

export interface PagedResponseBeleidskeuzeExtended {
    total: number
    offset?: number
    limit?: number
    results: BeleidskeuzeExtended[]
}

export interface PagedResponseBeleidsregelBasic {
    total: number
    offset?: number
    limit?: number
    results: BeleidsregelBasic[]
}

export interface PagedResponseBeleidsregelExtended {
    total: number
    offset?: number
    limit?: number
    results: BeleidsregelExtended[]
}

export interface PagedResponseDocumentBasic {
    total: number
    offset?: number
    limit?: number
    results: DocumentBasic[]
}

export interface PagedResponseDocumentExtended {
    total: number
    offset?: number
    limit?: number
    results: DocumentExtended[]
}

export interface PagedResponseGebiedBasic {
    total: number
    offset?: number
    limit?: number
    results: GebiedBasic[]
}

export interface PagedResponseGebiedExtended {
    total: number
    offset?: number
    limit?: number
    results: GebiedExtended[]
}

export interface PagedResponseGebiedengroepBasic {
    total: number
    offset?: number
    limit?: number
    results: GebiedengroepBasic[]
}

export interface PagedResponseGebiedengroepExtended {
    total: number
    offset?: number
    limit?: number
    results: GebiedengroepExtended[]
}

export interface PagedResponseGebiedsaanwijzingBasic {
    total: number
    offset?: number
    limit?: number
    results: GebiedsaanwijzingBasic[]
}

export interface PagedResponseGebiedsaanwijzingExtended {
    total: number
    offset?: number
    limit?: number
    results: GebiedsaanwijzingExtended[]
}

export interface PagedResponseGebiedsprogrammaBasic {
    total: number
    offset?: number
    limit?: number
    results: GebiedsprogrammaBasic[]
}

export interface PagedResponseGebiedsprogrammaExtended {
    total: number
    offset?: number
    limit?: number
    results: GebiedsprogrammaExtended[]
}

export interface PagedResponseHoofdlijn {
    total: number
    offset?: number
    limit?: number
    results: Hoofdlijn[]
}

export interface PagedResponseInputGeoWerkingsgebied {
    total: number
    offset?: number
    limit?: number
    results: InputGeoWerkingsgebied[]
}

export interface PagedResponseMaatregelBasic {
    total: number
    offset?: number
    limit?: number
    results: MaatregelBasic[]
}

export interface PagedResponseMaatregelExtended {
    total: number
    offset?: number
    limit?: number
    results: MaatregelExtended[]
}

export interface PagedResponseModuleObjectsResponseUnionAmbitieBasicBeleidsdoelBasicBeleidskeuzeBasicBeleidsregelBasicDocumentBasicGebiedsprogrammaBasicMaatregelBasicNationaalBelangBasicGebiedengroepBasicGebiedBasicGebiedsaanwijzingBasicProgrammaAlgemeenBasicVerplichtProgrammaBasicVisieAlgemeenBasicWerkingsgebiedBasicWettelijkeTaakBasic {
    total: number
    offset?: number
    limit?: number
    results: ModuleObjectsResponseUnionAmbitieBasicBeleidsdoelBasicBeleidskeuzeBasicBeleidsregelBasicDocumentBasicGebiedsprogrammaBasicMaatregelBasicNationaalBelangBasicGebiedengroepBasicGebiedBasicGebiedsaanwijzingBasicProgrammaAlgemeenBasicVerplichtProgrammaBasicVisieAlgemeenBasicWerkingsgebiedBasicWettelijkeTaakBasic[]
}

export interface PagedResponseModule {
    total: number
    offset?: number
    limit?: number
    results: Module[]
}

export interface PagedResponseNationaalBelangBasic {
    total: number
    offset?: number
    limit?: number
    results: NationaalBelangBasic[]
}

export interface PagedResponseObjectListAllLatestResponseUnionAmbitieBasicBeleidsdoelBasicBeleidskeuzeBasicBeleidsregelBasicDocumentBasicGebiedsprogrammaBasicMaatregelBasicNationaalBelangBasicGebiedengroepBasicGebiedBasicGebiedsaanwijzingBasicProgrammaAlgemeenBasicVerplichtProgrammaBasicVisieAlgemeenBasicWerkingsgebiedBasicWettelijkeTaakBasic {
    total: number
    offset?: number
    limit?: number
    results: ObjectListAllLatestResponseUnionAmbitieBasicBeleidsdoelBasicBeleidskeuzeBasicBeleidsregelBasicDocumentBasicGebiedsprogrammaBasicMaatregelBasicNationaalBelangBasicGebiedengroepBasicGebiedBasicGebiedsaanwijzingBasicProgrammaAlgemeenBasicVerplichtProgrammaBasicVisieAlgemeenBasicWerkingsgebiedBasicWettelijkeTaakBasic[]
}

export interface PagedResponseProgrammaAlgemeenBasic {
    total: number
    offset?: number
    limit?: number
    results: ProgrammaAlgemeenBasic[]
}

export interface ProgrammaAlgemeenExtendedStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface ProgrammaAlgemeenExtended {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    ObjectStatics?: ProgrammaAlgemeenExtendedStatics
}

export interface PagedResponseProgrammaAlgemeenExtended {
    total: number
    offset?: number
    limit?: number
    results: ProgrammaAlgemeenExtended[]
}

export interface PublicModuleShort {
    Module_ID: number
    Title: string
    Description: string
    Status?: ModuleStatus | null
}

export interface PagedResponsePublicModuleShort {
    total: number
    offset?: number
    limit?: number
    results: PublicModuleShort[]
}

export interface PublicationAOJ {
    UUID: string
    Administrative_Borders_ID: string
    Administrative_Borders_Domain: string
    Administrative_Borders_Date: string
    Created_Date: string
}

export interface PagedResponsePublicationAOJ {
    total: number
    offset?: number
    limit?: number
    results: PublicationAOJ[]
}

export interface PublicationActPackageReportShort {
    UUID: string
    Act_Package_UUID: string
    Report_Status: string
    Filename: string
    Main_Outcome: string
    Created_Date: string
}

export interface PagedResponsePublicationActPackageReportShort {
    total: number
    offset?: number
    limit?: number
    results: PublicationActPackageReportShort[]
}

export interface PublicationActPackage {
    UUID: string
    Package_Type: string
    Report_Status: string
    Delivery_ID: string
    Created_Date: string
    Modified_Date: string
    Created_By_UUID: string
    Modified_By_UUID: string
    Zip: PackageZipShort
    Module_ID?: number | null
    Module_Status?: ModuleStatus | null
}

export interface PagedResponsePublicationActPackage {
    total: number
    offset?: number
    limit?: number
    results: PublicationActPackage[]
}

export interface PublicationActShort {
    UUID: string
    Title: string
    Is_Active: boolean
    Environment_UUID: string
    Document_Type: string
    Work_Province_ID: string
    Work_Country: string
    Work_Date: string
    Work_Other: string
    Created_Date: string
    Modified_Date: string
}

export interface PagedResponsePublicationActShort {
    total: number
    offset?: number
    limit?: number
    results: PublicationActShort[]
}

export interface PublicationAnnouncementPackageReportShort {
    UUID: string
    Announcement_Package_UUID: string
    Report_Status: string
    Filename: string
    Main_Outcome: string
    Created_Date: string
}

export interface PagedResponsePublicationAnnouncementPackageReportShort {
    total: number
    offset?: number
    limit?: number
    results: PublicationAnnouncementPackageReportShort[]
}

export type PublicationAnnouncementShortMetadata = { [key: string]: unknown }

export interface PublicationAnnouncementShort {
    UUID: string
    Metadata: PublicationAnnouncementShortMetadata
    Announcement_Date?: string | null
    Is_Locked: boolean
    Created_Date: string
    Modified_Date: string
}

export interface PagedResponsePublicationAnnouncementShort {
    total: number
    offset?: number
    limit?: number
    results: PublicationAnnouncementShort[]
}

export interface PublicationEnvironment {
    UUID: string
    Title: string
    Description: string
    Province_ID: string
    Authority_ID: string
    Submitter_ID: string
    Governing_Body_Type: string
    Frbr_Country: string
    Frbr_Language: string
    Is_Active: boolean
    Has_State: boolean
    Can_Validate: boolean
    Can_Publicate: boolean
    Is_Locked: boolean
    Created_Date: string
    Modified_Date: string
}

export interface PagedResponsePublicationEnvironment {
    total: number
    offset?: number
    limit?: number
    results: PublicationEnvironment[]
}

export interface PublicationPackage {
    UUID: string
    Package_Type: string
    Report_Status: string
    Delivery_ID: string
    Created_Date: string
    Modified_Date: string
    Created_By_UUID: string
    Modified_By_UUID: string
    Zip: PackageZipShort
}

export interface PagedResponsePublicationPackage {
    total: number
    offset?: number
    limit?: number
    results: PublicationPackage[]
}

export interface PublicationTemplate {
    UUID: string
    Title: string
    Description: string
    Is_Active: boolean
    Document_Type: string
    Object_Types?: unknown
    Text_Template: string
    Object_Templates?: unknown
    Object_Field_Map?: unknown
    Created_Date: string
    Modified_Date: string
}

export interface PagedResponsePublicationTemplate {
    total: number
    offset?: number
    limit?: number
    results: PublicationTemplate[]
}

export type PublicationVersionStatus =
    (typeof PublicationVersionStatus)[keyof typeof PublicationVersionStatus]

export const PublicationVersionStatus = {
    not_applicable: 'not_applicable',
    active: 'active',
    validation: 'validation',
    validation_failed: 'validation_failed',
    publication: 'publication',
    publication_failed: 'publication_failed',
    publication_aborted: 'publication_aborted',
    announcement: 'announcement',
    completed: 'completed',
} as const

export interface Procedural {
    Enactment_Date?: string | null
    Signed_Date?: string | null
    Procedural_Announcement_Date?: string | null
}

export interface PublicationPackageShort {
    UUID: string
    Package_Type: string
    Report_Status: string
    Delivery_ID: string
    Created_Date: string
    Modified_Date: string
    Created_By_UUID: string
    Modified_By_UUID: string
}

export type PublicationVersionShortBillMetadata = { [key: string]: unknown }

export interface PublicationVersionShort {
    UUID: string
    Publication_UUID: string
    Module_Status: ModuleStatus
    Bill_Metadata: PublicationVersionShortBillMetadata
    Effective_Date?: string | null
    Announcement_Date?: string | null
    Is_Locked: boolean
    Status: PublicationVersionStatus
    Procedural?: Procedural | null
    Created_Date: string
    Modified_Date: string
    Act_Packages: PublicationPackageShort[]
}

export interface PagedResponsePublicationVersionShort {
    total: number
    offset?: number
    limit?: number
    results: PublicationVersionShort[]
}

export interface Publication {
    UUID: string
    Module_ID: number
    Is_Locked: boolean
    Document_Type: string
    Procedure_Type: string
    Template_UUID?: string | null
    Environment_UUID?: string | null
    Act_UUID?: string | null
    Created_Date: string
    Modified_Date: string
}

export interface PagedResponsePublication {
    total: number
    offset?: number
    limit?: number
    results: Publication[]
}

export interface SearchObjectUnionAmbitieBasicBeleidsdoelBasicBeleidskeuzeBasicBeleidsregelBasicDocumentBasicGebiedsprogrammaBasicMaatregelBasicNationaalBelangBasicGebiedengroepBasicGebiedBasicGebiedsaanwijzingBasicProgrammaAlgemeenBasicVerplichtProgrammaBasicVisieAlgemeenBasicWerkingsgebiedBasicWettelijkeTaakBasic {
    Module_ID?: number | null
    Object_Type: string
    Title: string
    Description: string
    Model:
        | AmbitieBasic
        | BeleidsdoelBasic
        | BeleidskeuzeBasic
        | BeleidsregelBasic
        | DocumentBasic
        | GebiedsprogrammaBasic
        | MaatregelBasic
        | NationaalBelangBasic
        | GebiedengroepBasic
        | GebiedBasic
        | GebiedsaanwijzingBasic
        | ProgrammaAlgemeenBasic
        | VerplichtProgrammaBasic
        | VisieAlgemeenBasic
        | WerkingsgebiedBasic
        | WettelijkeTaakBasic
}

export interface PagedResponseSearchObjectUnionAmbitieBasicBeleidsdoelBasicBeleidskeuzeBasicBeleidsregelBasicDocumentBasicGebiedsprogrammaBasicMaatregelBasicNationaalBelangBasicGebiedengroepBasicGebiedBasicGebiedsaanwijzingBasicProgrammaAlgemeenBasicVerplichtProgrammaBasicVisieAlgemeenBasicWerkingsgebiedBasicWettelijkeTaakBasic {
    total: number
    offset?: number
    limit?: number
    results: SearchObjectUnionAmbitieBasicBeleidsdoelBasicBeleidskeuzeBasicBeleidsregelBasicDocumentBasicGebiedsprogrammaBasicMaatregelBasicNationaalBelangBasicGebiedengroepBasicGebiedBasicGebiedsaanwijzingBasicProgrammaAlgemeenBasicVerplichtProgrammaBasicVisieAlgemeenBasicWerkingsgebiedBasicWettelijkeTaakBasic[]
}

export interface PagedResponseStorageFileBasic {
    total: number
    offset?: number
    limit?: number
    results: StorageFileBasic[]
}

export interface UnifiedPackage {
    Publication_Type: string
    UUID: string
    Created_Date: string
    Modified_Date: string
    Package_Type: string
    Report_Status: string
    Delivery_ID: string
    Module_ID: number
    Module_Title: string
    Document_Type: string
    Environment_UUID: string
}

export interface PagedResponseUnifiedPackage {
    total: number
    offset?: number
    limit?: number
    results: UnifiedPackage[]
}

export interface User {
    UUID: string
    Gebruikersnaam: string
    Email: string
    Roles: string[]
    Status: string
    IsActive: boolean
}

export interface PagedResponseUser {
    total: number
    offset?: number
    limit?: number
    results: User[]
}

export interface ValidSearchObjectUnionAmbitieBasicBeleidsdoelBasicBeleidskeuzeBasicBeleidsregelBasicDocumentBasicGebiedsprogrammaBasicMaatregelBasicNationaalBelangBasicGebiedengroepBasicGebiedBasicGebiedsaanwijzingBasicProgrammaAlgemeenBasicVerplichtProgrammaBasicVisieAlgemeenBasicWerkingsgebiedBasicWettelijkeTaakBasic {
    Object_Type: string
    Description: string
    Score: number
    Model:
        | AmbitieBasic
        | BeleidsdoelBasic
        | BeleidskeuzeBasic
        | BeleidsregelBasic
        | DocumentBasic
        | GebiedsprogrammaBasic
        | MaatregelBasic
        | NationaalBelangBasic
        | GebiedengroepBasic
        | GebiedBasic
        | GebiedsaanwijzingBasic
        | ProgrammaAlgemeenBasic
        | VerplichtProgrammaBasic
        | VisieAlgemeenBasic
        | WerkingsgebiedBasic
        | WettelijkeTaakBasic
}

export interface PagedResponseValidSearchObjectUnionAmbitieBasicBeleidsdoelBasicBeleidskeuzeBasicBeleidsregelBasicDocumentBasicGebiedsprogrammaBasicMaatregelBasicNationaalBelangBasicGebiedengroepBasicGebiedBasicGebiedsaanwijzingBasicProgrammaAlgemeenBasicVerplichtProgrammaBasicVisieAlgemeenBasicWerkingsgebiedBasicWettelijkeTaakBasic {
    total: number
    offset?: number
    limit?: number
    results: ValidSearchObjectUnionAmbitieBasicBeleidsdoelBasicBeleidskeuzeBasicBeleidsregelBasicDocumentBasicGebiedsprogrammaBasicMaatregelBasicNationaalBelangBasicGebiedengroepBasicGebiedBasicGebiedsaanwijzingBasicProgrammaAlgemeenBasicVerplichtProgrammaBasicVisieAlgemeenBasicWerkingsgebiedBasicWettelijkeTaakBasic[]
}

export interface PagedResponseVerplichtProgrammaBasic {
    total: number
    offset?: number
    limit?: number
    results: VerplichtProgrammaBasic[]
}

export interface PagedResponseVisieAlgemeenBasic {
    total: number
    offset?: number
    limit?: number
    results: VisieAlgemeenBasic[]
}

export interface VisieAlgemeenExtendedStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface VisieAlgemeenExtended {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    ObjectStatics?: VisieAlgemeenExtendedStatics
}

export interface PagedResponseVisieAlgemeenExtended {
    total: number
    offset?: number
    limit?: number
    results: VisieAlgemeenExtended[]
}

export interface PagedResponseWerkingsgebiedBasic {
    total: number
    offset?: number
    limit?: number
    results: WerkingsgebiedBasic[]
}

export interface WerkingsgebiedExtendedStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface WerkingsgebiedExtended {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Area_UUID?: string | null
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    ObjectStatics?: WerkingsgebiedExtendedStatics
}

export interface PagedResponseWerkingsgebiedExtended {
    total: number
    offset?: number
    limit?: number
    results: WerkingsgebiedExtended[]
}

export interface Werkingsgebied {
    ID?: number | null
    UUID: string
    Created_Date: string
    Modified_Date: string
    Title: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Geometry_Hash?: string | null
}

export interface PagedResponseWerkingsgebied {
    total: number
    offset?: number
    limit?: number
    results: Werkingsgebied[]
}

export interface PagedResponseWettelijkeTaakBasic {
    total: number
    offset?: number
    limit?: number
    results: WettelijkeTaakBasic[]
}

export interface PatchResponse {
    UUID: string
}

export type ProcedureType = (typeof ProcedureType)[keyof typeof ProcedureType]

export const ProcedureType = {
    draft: 'draft',
    final: 'final',
} as const

export interface ProgrammaAlgemeenFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface ProgrammaAlgemeenFull {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Description?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Gebiedsaanwijzingen_Statics?: ObjectStatics[]
    Public_Revisions?: PublicModuleObjectRevision[]
    Next_Version?: NextObjectVersion | null
    ObjectStatics?: ProgrammaAlgemeenFullStatics
}

export interface ProgrammaAlgemeenStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
}

export interface ProgrammaAlgemeenStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface ProgrammaAlgemeenUUID {
    Object_ID?: number
    UUID?: string
}

export interface PublicModuleObjectContextShort {
    Action: string
    Original_Adjust_On?: string | null
}

export interface PublicModuleObjectShort {
    Module_ID: number
    UUID: string
    Object_Type: string
    Object_ID: number
    Code: string
    Description: string
    Modified_Date: string
    Title: string
    ModuleObjectContext?: PublicModuleObjectContextShort | null
}

export interface PublicModuleOverview {
    Module: PublicModuleShort
    Objects: PublicModuleObjectShort[]
}

export type PublicationActMetadata = { [key: string]: unknown }

export interface PublicationAct {
    UUID: string
    Title: string
    Is_Active: boolean
    Environment: PublicationEnvironment
    Document_Type: string
    Metadata: PublicationActMetadata
    Work_Province_ID: string
    Work_Country: string
    Work_Date: string
    Work_Other: string
    Created_Date: string
    Modified_Date: string
}

export interface PublicationActPackageDetailResponse {
    UUID: string
    Package_Type: string
    Report_Status: string
    Delivery_ID: string
    Document_Type: string
    Publication_Version_UUID: string
    Bill_Version_UUID: string | null
    Act_Version_UUID: string | null
    Zip: PackageZipShort
    Created_Environment_State_UUID: string | null
    Used_Environment_State_UUID: string | null
    Created_Date: string
    Modified_Date: string
    Created_By_UUID: string
    Modified_By_UUID: string
    Module_ID: number | null
    Module_Title: string | null
    Module_Status_ID: number | null
    Module_Status_Status: string | null
    Environment_UUID: string
    Environment_Title: string
}

export interface PublicationActPackageReport {
    UUID: string
    Act_Package_UUID: string
    Report_Status: string
    Filename: string
    Source_Document: string
    Main_Outcome: string
    Sub_Delivery_ID: string
    Sub_Progress: string
    Sub_Outcome: string
    Created_Date: string
}

export type PublicationAnnouncementMetadata = { [key: string]: unknown }

export type PublicationAnnouncementProcedural = { [key: string]: unknown }

export type PublicationAnnouncementContent = { [key: string]: unknown }

export interface PublicationShort {
    UUID: string
    Module_ID: number
    Is_Locked: boolean
    Document_Type: string
    Procedure_Type: string
    Template_UUID?: string | null
    Environment_UUID?: string | null
    Act_UUID?: string | null
    Created_Date: string
    Modified_Date: string
}

export interface PublicationAnnouncement {
    UUID: string
    Act_Package: PublicationPackageShort
    Publication: PublicationShort
    Metadata: PublicationAnnouncementMetadata
    Procedural: PublicationAnnouncementProcedural
    Content: PublicationAnnouncementContent
    Announcement_Date?: string | null
    Is_Locked: boolean
    Created_Date: string
    Modified_Date: string
}

export interface PublicationAnnouncementEdit {
    Announcement_Date?: string | null
    Metadata?: AnnouncementMetadata | null
    Procedural?: AnnouncementProcedural | null
    Content?: AnnouncementContent | null
}

export interface PublicationAnnouncementPackageCreate {
    Package_Type: PackageType
}

export interface PublicationAnnouncementPackageCreatedResponse {
    Package_UUID: string
    Zip_UUID: string
}

export interface PublicationAnnouncementPackageDetailResponse {
    UUID: string
    Package_Type: string
    Report_Status: string
    Delivery_ID: string
    Document_Type: string
    Announcement_UUID: string
    Doc_Version_UUID: string | null
    Zip: PackageZipShort
    Created_Environment_State_UUID: string | null
    Used_Environment_State_UUID: string | null
    Created_Date: string
    Modified_Date: string
    Created_By_UUID: string
    Modified_By_UUID: string
    Module_ID: number | null
    Module_Title: string | null
    Module_Status_ID: number | null
    Module_Status_Status: string | null
    Environment_UUID: string
    Environment_Title: string
}

export interface PublicationAnnouncementPackageReport {
    UUID: string
    Announcement_Package_UUID: string
    Report_Status: string
    Filename: string
    Source_Document: string
    Main_Outcome: string
    Sub_Delivery_ID: string
    Sub_Progress: string
    Sub_Outcome: string
    Created_Date: string
}

export interface PublicationCreate {
    Module_ID: number
    Document_Type: DocumentType
    Procedure_Type: ProcedureType
    Template_UUID: string
    Environment_UUID: string
    Act_UUID: string
}

export interface PublicationCreatedResponse {
    UUID: string
}

export interface PublicationEdit {
    Template_UUID?: string | null
}

export interface PublicationPackageCreate {
    Package_Type: PackageType
}

export interface PublicationPackageCreatedResponse {
    Package_UUID: string
    Zip_UUID: string
}

export interface PublicationPackagePdf {
    Mutation?: MutationStrategy | null
}

export type PublicationType =
    (typeof PublicationType)[keyof typeof PublicationType]

export const PublicationType = {
    act: 'act',
    announcement: 'announcement',
} as const

export type PublicationVersionBillMetadata = { [key: string]: unknown }

export type PublicationVersionBillCompact = { [key: string]: unknown }

export type PublicationVersionProcedural = { [key: string]: unknown }

export interface PublicationVersion {
    UUID: string
    Publication: PublicationShort
    Module_Status: ModuleStatus
    Bill_Metadata: PublicationVersionBillMetadata
    Bill_Compact: PublicationVersionBillCompact
    Procedural: PublicationVersionProcedural
    Effective_Date?: string | null
    Announcement_Date?: string | null
    Is_Locked: boolean
    Status: PublicationVersionStatus
    Mutation_Strategy: MutationStrategy
    Created_Date: string
    Modified_Date: string
    Attachments: AttachmentShort[]
    Errors?: ErrorDetails[]
}

export interface PublicationVersionCreate {
    Module_Status_ID: number
    Mutation_Strategy?: MutationStrategy
}

export interface PublicationVersionCreatedResponse {
    UUID: string
}

export interface PublicationVersionEdit {
    Module_Status_ID?: number | null
    Effective_Date?: string | null
    Announcement_Date?: string | null
    Mutation_Strategy?: MutationStrategy | null
    Bill_Metadata?: BillMetadata | null
    Bill_Compact?: BillCompact | null
    Procedural?: Procedural | null
}

export interface PublicationVersionEditResponse {
    Errors: ErrorDetails[]
    Is_Valid: boolean
}

export interface ReadRelation {
    Object_ID: number
    Object_Type: string
    Description?: string
    Title?: string
}

export type ReportStatusType =
    (typeof ReportStatusType)[keyof typeof ReportStatusType]

export const ReportStatusType = {
    not_applicable: 'not_applicable',
    pending: 'pending',
    valid: 'valid',
    failed: 'failed',
    aborted: 'aborted',
} as const

export interface RequestAcknowledgedRelation {
    Object_ID: number
    Object_Type: string
    Explanation?: string | null
}

export interface RequestData {
    object_types?: string[]
    module_id?: number | null
    /** Search in Objects? */
    include_valids?: boolean
    /** Search in Module Objects? */
    include_modules?: boolean
    /** @minLength 1 */
    query: string
}

export interface ResetPasswordResponse {
    UUID: string
    NewPassword: string
}

export interface ResponseOK {
    message?: string
}

export type RootModelListObjectCount = ObjectCount[]

export interface SearchRequestData {
    Object_Types?: string[] | null
}

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]

export const SortOrder = {
    ASC: 'ASC',
    DESC: 'DESC',
} as const

export type TemplateCreateObjectFieldMap = { [key: string]: string[] }

export type TemplateCreateObjectTemplates = { [key: string]: string }

export interface TemplateCreate {
    /** @minLength 3 */
    Title: string
    Description: string
    Document_Type: DocumentType
    Object_Types: string[]
    Object_Field_Map: TemplateCreateObjectFieldMap
    Text_Template: string
    Object_Templates: TemplateCreateObjectTemplates
}

export interface TemplateCreatedResponse {
    UUID: string
}

export type TemplateEditObjectFieldMap = { [key: string]: string[] } | null

export type TemplateEditObjectTemplates = { [key: string]: string } | null

export interface TemplateEdit {
    Title?: string | null
    Description?: string | null
    Is_Active?: boolean | null
    Document_Type?: DocumentType | null
    /** @deprecated */
    Field_Map?: string[] | null
    Object_Field_Map?: TemplateEditObjectFieldMap
    Object_Types?: string[] | null
    Text_Template?: string | null
    Object_Templates?: TemplateEditObjectTemplates
}

export interface UploadAttachmentResponse {
    ID: number
}

export interface UploadFileResponse {
    UUID: string
}

export interface UploadPackageReportResponse {
    Status: ReportStatusType
    Duplicate_Count: number
}

export interface UserCreate {
    /** @minLength 3 */
    Gebruikersnaam: string
    Email: string
    Roles: string[]
}

export interface UserCreateResponse {
    UUID: string
    Email: string
    Roles: string[]
    Password: string
}

export interface ValidateModuleObject {
    code: string
    object_id: number
    object_type: string
    title: string
}

export type ValidateModuleSeverity =
    (typeof ValidateModuleSeverity)[keyof typeof ValidateModuleSeverity]

export const ValidateModuleSeverity = {
    info: 'info',
    warning: 'warning',
    error: 'error',
} as const

export interface ValidateModuleError {
    rule: string
    object: ValidateModuleObject
    messages: string[]
    severity?: ValidateModuleSeverity
}

export interface ValidateModuleResult {
    errors: ValidateModuleError[]
    readonly status: string
}

export interface VerplichtProgrammaCreateStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
}

export interface VerplichtProgrammaCreate {
    Title?: string
    Description?: string | null
    ObjectStatics?: VerplichtProgrammaCreateStatics
}

export interface VerplichtProgrammaEdit {
    Title?: string | null
    Description?: string | null
}

export interface VerplichtProgrammaFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface VerplichtProgrammaFull {
    Object_Type?: string
    Object_ID?: number
    Code?: string
    UUID?: string
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Description?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    WettelijkeTaken?: WettelijkeTaakMinimal[]
    Maatregelen?: ReadRelationShortMaatregelMinimal[]
    ObjectStatics?: VerplichtProgrammaFullStatics
}

export interface VerplichtProgrammaMinimal {
    Object_Type?: string
    Object_ID?: number
    Code?: string
    UUID?: string
    Created_Date?: string
    Modified_Date?: string
    Title?: string
}

export interface VerplichtProgrammaStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
}

export interface VerplichtProgrammaStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface VerplichtProgrammaUUID {
    Object_ID?: number
    UUID?: string
}

export interface VisieAlgemeenFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface VisieAlgemeenFull {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Description?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Gebiedsaanwijzingen_Statics?: ObjectStatics[]
    Public_Revisions?: PublicModuleObjectRevision[]
    Next_Version?: NextObjectVersion | null
    ObjectStatics?: VisieAlgemeenFullStatics
}

export interface VisieAlgemeenStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
}

export interface VisieAlgemeenStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface VisieAlgemeenUUID {
    Object_ID?: number
    UUID?: string
}

export interface WerkingsgebiedRelatedObjectShort {
    UUID: string
    Object_Type: string
    Object_ID: number
    Title: string | null
    Werkingsgebied_Code: string
}

export interface WerkingsgebiedRelatedModuleObjectShort {
    UUID: string
    Object_Type: string
    Object_ID: number
    Title: string | null
    Werkingsgebied_Code: string
    Module_ID?: number | null
    Module_Title?: string | null
}

export interface WerkingsgebiedRelatedObjects {
    Valid_Objects: WerkingsgebiedRelatedObjectShort[]
    Module_Objects: WerkingsgebiedRelatedModuleObjectShort[]
}

export interface WerkingsgebiedFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface WerkingsgebiedFull {
    Object_ID?: number
    Code?: string
    UUID?: string
    Adjust_On?: string | null
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Description?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Area_UUID?: string | null
    Area?: AreaBasic | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    Related_Objects?: WerkingsgebiedRelatedObjects | null
    ObjectStatics?: WerkingsgebiedFullStatics
}

export interface WerkingsgebiedStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
}

export interface WerkingsgebiedStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface WerkingsgebiedUUID {
    Object_ID?: number
    UUID?: string
}

export interface WettelijkeTaakCreateStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
}

export interface WettelijkeTaakCreate {
    Title?: string
    Weblink?: string | null
    ObjectStatics?: WettelijkeTaakCreateStatics
}

export interface WettelijkeTaakEdit {
    Title?: string | null
    Weblink?: string | null
}

export interface WettelijkeTaakFullStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface WettelijkeTaakFull {
    Object_Type?: string
    Object_ID?: number
    Code?: string
    UUID?: string
    Created_Date?: string
    Modified_Date?: string
    Title?: string
    Weblink?: string
    Start_Validity?: string | null
    End_Validity?: string | null
    Created_By?: UserShort | null
    Modified_By?: UserShort | null
    VerplichtProgrammas?: VerplichtProgrammaMinimal[]
    Beleidskeuzes?: ReadRelationShortBeleidskeuzeMinimal[]
    ObjectStatics?: WettelijkeTaakFullStatics
}

export interface WettelijkeTaakStaticPostStatics {
    Owner_1_UUID?: string | null
    Owner_2_UUID?: string | null
}

export interface WettelijkeTaakStaticStatics {
    Owner_1?: UserShort | null
    Owner_2?: UserShort | null
}

export interface WettelijkeTaakUUID {
    Object_ID?: number
    UUID?: string
}

export interface WriteRelation {
    Object_ID: number
    Object_Type: string
    Description?: string
}

export type AuthenticationPostAuthResetPasswordParams = {
    password: string
    new_password: string
}

export type GraphGetObjectGraphParams = {
    uuid: string
}

export type HoofdlijnGetHoofdlijnenListParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type HoofdlijnPostHoofdlijnenSearchParams = {
    query: string
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type InputGeoGetInputGeoListLatestWerkingsgebiedenParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: InputGeoWerkingsgebiedenSortColumn | null
    sort_order?: SortOrder | null
}

export type InputGeoGetInputGeoWerkingsgebiedenHistoryParams = {
    title: string
    from_date?: string | null
}

export type ModulesGetListModulesParams = {
    only_mine?: boolean
    filter_activated?: boolean | null
    filter_closed?: boolean | null
    filter_successful?: boolean | null
    filter_title?: string | null
    object_type?: string | null
    lineage_id?: number | null
    offset?: number | null
    limit?: number | null
    sort_column?: ModuleSortColumn | null
    sort_order?: SortOrder | null
}

export type ModulesGetListModuleObjectsParams = {
    object_types?: string[]
    owner_uuid?: string | null
    owner_type?: OwnerType
    minimum_status?: ModuleStatusCode | null
    only_active_modules?: boolean
    title?: string | null
    actions?: ModuleObjectActionFull[]
    module_id?: number | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type ObjectRelatedFilesDeleteObjectRelatedFilesDeleteParams = {
    related_file_uuid: string
}

export type ObjectsDoListAllLatestParams = {
    object_types?: string[]
    owner_uuid?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type PublicModulesGetPublicListModulesParams = {
    offset?: number | null
    limit?: number | null
}

export type PublicationAojGetListAojParams = {
    offset?: number | null
    limit?: number | null
}

export type PublicationActPackagesGetListActPackagesParams = {
    version_uuid?: string | null
    package_type?: PackageType | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type PublicationActPackagesPostAbortActPackageParams = {
    confirm?: boolean
}

export type PublicationActReportsGetListActPackageReportsParams = {
    act_package_uuid?: string | null
    report_status?: ReportStatusType | null
    offset?: number | null
    limit?: number | null
}

export type PublicationActsGetListActsParams = {
    is_active?: boolean | null
    environment_uuid?: string | null
    document_type?: DocumentType | null
    procedure_type?: ProcedureType | null
    offset?: number | null
    limit?: number | null
}

export type PublicationAnnouncementPackagesGetListAnnouncementPackagesParams = {
    announcement_uuid?: string | null
    package_type?: PackageType | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type PublicationAnnouncementReportsGetListAnnnouncementPackageReportsParams =
    {
        announcement_package_uuid?: string | null
        report_status?: ReportStatusType | null
        offset?: number | null
        limit?: number | null
    }

export type PublicationAnnouncementsGetListAnnouncementsParams = {
    act_package_uuid?: string | null
    offset?: number | null
    limit?: number | null
}

export type PublicationEnvironmentsGetListEnvironmentsParams = {
    is_active?: boolean | null
    offset?: number | null
    limit?: number | null
}

export type PublicationPackagesGetListUnifiedPackagesParams = {
    environment_uuid?: string | null
    module_id?: number | null
    report_status?: ReportStatusType | null
    package_type?: PackageType | null
    document_type?: DocumentType | null
    publication_type?: PublicationType | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type PublicationTemplatesGetListTemplatesParams = {
    is_active?: boolean | null
    document_type?: DocumentType | null
    offset?: number | null
    limit?: number | null
}

export type PublicationVersionsGetListVersionsParams = {
    offset?: number | null
    limit?: number | null
}

export type PublicationsGetListPublicationsParams = {
    document_type?: DocumentType | null
    module_id?: number | null
    offset?: number | null
    limit?: number | null
}

export type SearchGetSearchParams = {
    offset?: number | null
    limit?: number | null
}

export type SearchGetMssqlValidSearchParams = {
    query: string
    offset?: number | null
    limit?: number | null
}

export type SourceWerkingsgebiedenGetListWerkingsgebiedenParams = {
    title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type StorageFileGetFilesListParams = {
    only_mine?: boolean
    filter_filename?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type UserGetListUsersParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type UserGetSearchUsersParams = {
    role?: string | null
    query?: string | null
    active?: boolean | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type AmbitieListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type AmbitieListValidLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type AmbitiePostModulePatchObjectBody = {
    Title?: string | null
    Description?: string | null
    Themas?: string[] | null
}

export type AmbitieGetModuleListLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type AmbitieGetListActiveModuleObjectsParams = {
    minimum_status: ModuleStatusCode
}

export type BeleidsdoelListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type BeleidsdoelListValidLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type BeleidsdoelPostModulePatchObjectBody = {
    Title?: string | null
    Description?: string | null
    Hierarchy_Code?: string | null
    Themas?: string[] | null
}

export type BeleidsdoelGetModuleListLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type BeleidsdoelGetListActiveModuleObjectsParams = {
    minimum_status: ModuleStatusCode
}

export type BeleidskeuzeListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type BeleidskeuzeListValidLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type BeleidskeuzeGetAcknowledgedRelationListParams = {
    requested_by_us?: boolean
    acknowledged?: boolean | null
    show_inactive?: boolean
}

export type BeleidskeuzePostModulePatchObjectBody = {
    Title?: string | null
    Description?: string | null
    Cause?: string | null
    Provincial_Interest?: string | null
    Explanation?: string | null
    Hierarchy_Code?: string | null
    Werkingsgebied_Code?: string | null
    Gebiedengroep_Code?: string | null
    Themas?: string[] | null
}

export type BeleidskeuzeGetModuleListLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type BeleidskeuzeGetListActiveModuleObjectsParams = {
    minimum_status: ModuleStatusCode
}

export type BeleidsregelListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type BeleidsregelListValidLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type BeleidsregelPostModulePatchObjectBody = {
    Title?: string | null
    Weblink?: string | null
    Description?: string | null
}

export type BeleidsregelGetModuleListLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type BeleidsregelGetListActiveModuleObjectsParams = {
    minimum_status: ModuleStatusCode
}

export type DocumentListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type DocumentListValidLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type DocumentPostModulePatchObjectBody = {
    Title?: string | null
    Filename?: string | null
    Description?: string | null
    File_UUID?: string | null
}

export type DocumentGetModuleListLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type DocumentGetListActiveModuleObjectsParams = {
    minimum_status: ModuleStatusCode
}

export type GebiedListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type GebiedListValidLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type GebiedPostModulePatchObjectBody = {
    Title?: string | null
}

export type GebiedGetModuleListLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type GebiedGetListActiveModuleObjectsParams = {
    minimum_status: ModuleStatusCode
}

export type GebiedengroepListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type GebiedengroepListValidLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type GebiedengroepPostModulePatchObjectBody = {
    Title?: string | null
    Source_Title?: string | null
    Description?: string | null
}

export type GebiedengroepGetModuleListLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type GebiedengroepGetListActiveModuleObjectsParams = {
    minimum_status: ModuleStatusCode
}

export type GebiedsaanwijzingListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type GebiedsaanwijzingListValidLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type GebiedsaanwijzingPostModulePatchObjectBody = {
    Title?: string | null
    Target_Codes?: string[]
    Ref_Type?: string
    Ref_Group?: string
}

export type GebiedsaanwijzingGetModuleListLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type GebiedsaanwijzingGetListActiveModuleObjectsParams = {
    minimum_status: ModuleStatusCode
}

export type GebiedsprogrammaListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type GebiedsprogrammaListValidLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type GebiedsprogrammaPostModulePatchObjectBody = {
    Title?: string | null
    Description?: string | null
    Image?: string | null
}

export type GebiedsprogrammaGetModuleListLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type GebiedsprogrammaGetListActiveModuleObjectsParams = {
    minimum_status: ModuleStatusCode
}

export type MaatregelListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type MaatregelListValidLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type MaatregelPostModulePatchObjectBody = {
    Title?: string | null
    Description?: string | null
    Role?: string | null
    Effect?: string | null
    Hierarchy_Code?: string | null
    Documents?: string[] | null
    Werkingsgebied_Code?: string | null
    Gebiedengroep_Code?: string | null
    Themas?: string[] | null
}

export type MaatregelGetModuleListLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type MaatregelGetListActiveModuleObjectsParams = {
    minimum_status: ModuleStatusCode
}

export type NationaalBelangListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type ProgrammaAlgemeenListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type ProgrammaAlgemeenListValidLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type ProgrammaAlgemeenPostModulePatchObjectBody = {
    Title?: string | null
    Description?: string | null
}

export type ProgrammaAlgemeenGetModuleListLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type ProgrammaAlgemeenGetListActiveModuleObjectsParams = {
    minimum_status: ModuleStatusCode
}

export type VerplichtProgrammaListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type VisieAlgemeenListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type VisieAlgemeenListValidLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type VisieAlgemeenPostModulePatchObjectBody = {
    Title?: string | null
    Description?: string | null
}

export type VisieAlgemeenGetModuleListLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type VisieAlgemeenGetListActiveModuleObjectsParams = {
    minimum_status: ModuleStatusCode
}

export type WerkingsgebiedListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type WerkingsgebiedListValidLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type WerkingsgebiedPostModulePatchObjectBody = {
    Title?: string | null
    Description?: string | null
    Area_UUID?: string | null
}

export type WerkingsgebiedGetModuleListLineageTreeParams = {
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}

export type WerkingsgebiedGetListActiveModuleObjectsParams = {
    minimum_status: ModuleStatusCode
}

export type WettelijkeTaakListValidLineagesParams = {
    filter_title?: string | null
    offset?: number | null
    limit?: number | null
    sort_column?: string | null
    sort_order?: SortOrder | null
}
