import React, { Component } from 'react';

class MainContent extends Component {
  render() {
    return (
    	<div>
        <h1 className="mb-8">Gezonde aantrekkelijke leefomgeving</h1>
        <p>De combinatie van het kenmerkende kust-, veenweide- en rivierdeltalandschap, waarin steden en landschap met elkaar verweven zijn, maakt onze provincie veelzijdig en uniek. Een landschap met 12<br/>belangrijke leefgebieden voor plant- en diersoorten. Met prachtige open gebieden en een rijk cultureel erfgoed van aantrekkelijke historische steden, landgoederen en molens.<br/><br/>Ons landschap en de biodiversiteit staan onder druk door het groeiend aantal inwoners, economische ontwikkeling en de klimaatverandering. Er is behoefte aan meer woningen en ruimte voor bedrijvigheid. De landbouwsector, op veel plaatsen drager van het landschap, heeft te kampen met bodemdaling en druk op schaalvergroting vanuit de wereldmarkt. Tegelijkertijd groeit het besef dat het landschap ook een belangrijke concurrentiefactor is. Een kwaliteit die wordt bedreigd door verstedelijking en oprukkende bedrijvigheid. In metropolitane regio’s is een aantrekkelijk landelijk gebied een belangrijke vestigingsfactor voor mensen en bedrijven en een essentieel onderdeel van de leefomgevingskwaliteit voor inwoners, werknemers, recreanten en toeristen. Een groene leefomgeving draagt bij aan een gezonde leefstijl van de inwoners van Zuid-Holland.<br/><br/>De provincie Zuid-Holland wil de kwaliteit van de leefomgeving versterken door natuur, water, recreatie, landbouw, cultureel erfgoed en economie in samenhang te bezien. We beschermen de bijzondere kwaliteiten van ons landschap, ook om de groenbeleving van inwoners, recreanten en toeristen te<br/>verbeteren. We benutten natuur, cultureel erfgoed en monumenten om het landschap aantrekkelijk te maken en te houden. Daarbij willen we de biodiversiteit vergroten, natuurinclusieve landbouw geven we de ruimte. Dit draagt bij aan een fijnmazig natuurnatuurnetwerk. Ook zetten we in op diervriendelijke veehouderij. Onze inzet richt zich niet enkel op het landelijk gebied. Aantrekkelijke landschappen reiken tot in de stad en het stedelijk gebied reikt tot in de landschappen. We streven naar een zachte overgang van<br/>het stedelijk- naar het landelijk gebied, waarbij kwaliteit centraal staat.<br/><br/>Hierbij spelen in Zuid-Holland onder meer de volgende opgaven:<br/>- behouden en waar mogelijk versterken van biodiversiteit;<br/>- natuurontwikkeling (realisatie Natuur Netwerk Nederland én vormgeven twee Nationale Parken);<br/>- ontwikkeling van groen en blauw in en om de stad;<br/>- ontwikkeling vitale metropolitane landschappen;<br/>- versterken van de landgoederenzone;<br/>- beleefbaar maken van cultureel erfgoed;<br/>- ontwikkeling natuurinclusieve landbouw;<br/>- verbetering luchtkwaliteit door beperken emissies (o.a. terugdringing stikstofuitstoot).<br/><br/>De ambitie ‘Gezonde en aantrekkelijke leefomgeving’ wordt onder andere uitgewerkt in de ‘Visie Rijke Groenblauwe Leefomgeving’.</p>
			</div>
    );
  }
}

export default MainContent;